// <auto-generated/>
using EtherSharp.ABI.Types;
using EtherSharp.Types;

namespace EtherSharp.ABI.Packed;

public partial class PackedAbiEncoder
{
    /// <summary>
    /// Encodes a bytes1 value in packed format.
    /// </summary>
    /// <param name="value">The byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes1(Bytes1 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes1>(value));
    /// <summary>
    /// Encodes a bytes2 value in packed format.
    /// </summary>
    /// <param name="value">The 2-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes2(Bytes2 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes2>(value));
    /// <summary>
    /// Encodes a bytes3 value in packed format.
    /// </summary>
    /// <param name="value">The 3-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes3(Bytes3 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes3>(value));
    /// <summary>
    /// Encodes a bytes4 value in packed format.
    /// </summary>
    /// <param name="value">The 4-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes4(Bytes4 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes4>(value));
    /// <summary>
    /// Encodes a bytes5 value in packed format.
    /// </summary>
    /// <param name="value">The 5-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes5(Bytes5 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes5>(value));
    /// <summary>
    /// Encodes a bytes6 value in packed format.
    /// </summary>
    /// <param name="value">The 6-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes6(Bytes6 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes6>(value));
    /// <summary>
    /// Encodes a bytes7 value in packed format.
    /// </summary>
    /// <param name="value">The 7-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes7(Bytes7 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes7>(value));
    /// <summary>
    /// Encodes a bytes8 value in packed format.
    /// </summary>
    /// <param name="value">The 8-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes8(Bytes8 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes8>(value));
    /// <summary>
    /// Encodes a bytes9 value in packed format.
    /// </summary>
    /// <param name="value">The 9-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes9(Bytes9 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes9>(value));
    /// <summary>
    /// Encodes a bytes10 value in packed format.
    /// </summary>
    /// <param name="value">The 10-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes10(Bytes10 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes10>(value));
    /// <summary>
    /// Encodes a bytes11 value in packed format.
    /// </summary>
    /// <param name="value">The 11-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes11(Bytes11 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes11>(value));
    /// <summary>
    /// Encodes a bytes12 value in packed format.
    /// </summary>
    /// <param name="value">The 12-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes12(Bytes12 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes12>(value));
    /// <summary>
    /// Encodes a bytes13 value in packed format.
    /// </summary>
    /// <param name="value">The 13-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes13(Bytes13 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes13>(value));
    /// <summary>
    /// Encodes a bytes14 value in packed format.
    /// </summary>
    /// <param name="value">The 14-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes14(Bytes14 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes14>(value));
    /// <summary>
    /// Encodes a bytes15 value in packed format.
    /// </summary>
    /// <param name="value">The 15-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes15(Bytes15 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes15>(value));
    /// <summary>
    /// Encodes a bytes16 value in packed format.
    /// </summary>
    /// <param name="value">The 16-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes16(Bytes16 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes16>(value));
    /// <summary>
    /// Encodes a bytes17 value in packed format.
    /// </summary>
    /// <param name="value">The 17-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes17(Bytes17 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes17>(value));
    /// <summary>
    /// Encodes a bytes18 value in packed format.
    /// </summary>
    /// <param name="value">The 18-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes18(Bytes18 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes18>(value));
    /// <summary>
    /// Encodes a bytes19 value in packed format.
    /// </summary>
    /// <param name="value">The 19-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes19(Bytes19 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes19>(value));
    /// <summary>
    /// Encodes a bytes20 value in packed format.
    /// </summary>
    /// <param name="value">The 20-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes20(Bytes20 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes20>(value));
    /// <summary>
    /// Encodes a bytes21 value in packed format.
    /// </summary>
    /// <param name="value">The 21-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes21(Bytes21 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes21>(value));
    /// <summary>
    /// Encodes a bytes22 value in packed format.
    /// </summary>
    /// <param name="value">The 22-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes22(Bytes22 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes22>(value));
    /// <summary>
    /// Encodes a bytes23 value in packed format.
    /// </summary>
    /// <param name="value">The 23-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes23(Bytes23 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes23>(value));
    /// <summary>
    /// Encodes a bytes24 value in packed format.
    /// </summary>
    /// <param name="value">The 24-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes24(Bytes24 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes24>(value));
    /// <summary>
    /// Encodes a bytes25 value in packed format.
    /// </summary>
    /// <param name="value">The 25-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes25(Bytes25 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes25>(value));
    /// <summary>
    /// Encodes a bytes26 value in packed format.
    /// </summary>
    /// <param name="value">The 26-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes26(Bytes26 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes26>(value));
    /// <summary>
    /// Encodes a bytes27 value in packed format.
    /// </summary>
    /// <param name="value">The 27-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes27(Bytes27 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes27>(value));
    /// <summary>
    /// Encodes a bytes28 value in packed format.
    /// </summary>
    /// <param name="value">The 28-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes28(Bytes28 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes28>(value));
    /// <summary>
    /// Encodes a bytes29 value in packed format.
    /// </summary>
    /// <param name="value">The 29-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes29(Bytes29 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes29>(value));
    /// <summary>
    /// Encodes a bytes30 value in packed format.
    /// </summary>
    /// <param name="value">The 30-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes30(Bytes30 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes30>(value));
    /// <summary>
    /// Encodes a bytes31 value in packed format.
    /// </summary>
    /// <param name="value">The 31-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes31(Bytes31 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes31>(value));
    /// <summary>
    /// Encodes a bytes32 value in packed format.
    /// </summary>
    /// <param name="value">The 32-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Bytes32(Bytes32 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes32>(value));

}
