// <auto-generated/>
using EtherSharp.ABI.Types;
using EtherSharp.Numerics;

namespace EtherSharp.ABI.Packed;

public partial class PackedAbiEncoder
{
    /// <summary>
    /// Encodes a uint8 value in packed format.
    /// </summary>
    /// <param name="value">The byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt8(byte value)
        => AddElement(new AbiTypes.Byte(value));

    /// <summary>
    /// Encodes an int8 value in packed format.
    /// </summary>
    /// <param name="value">The signed byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int8(sbyte value)
        => AddElement(new AbiTypes.SByte(value));

    /// <summary>
    /// Encodes a uint16 value in packed format.
    /// </summary>
    /// <param name="value">The unsigned short value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt16(ushort value)
        => AddElement(new AbiTypes.UShort(value));

    /// <summary>
    /// Encodes an int16 value in packed format.
    /// </summary>
    /// <param name="value">The short value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int16(short value)
        => AddElement(new AbiTypes.Short(value));


    /// <summary>
    /// Encodes an int24 value in packed format.
    /// </summary>
    /// <param name="value">The int value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int24(int value)
        => AddElement(new AbiTypes.Int(value, 3));

    /// <summary>
    /// Encodes a uint24 value in packed format.
    /// </summary>
    /// <param name="value">The uint value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt24(uint value)
        => AddElement(new AbiTypes.UInt(value, 3));

    /// <summary>
    /// Encodes an int32 value in packed format.
    /// </summary>
    /// <param name="value">The int value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int32(int value)
        => AddElement(new AbiTypes.Int(value, 4));

    /// <summary>
    /// Encodes a uint32 value in packed format.
    /// </summary>
    /// <param name="value">The uint value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt32(uint value)
        => AddElement(new AbiTypes.UInt(value, 4));


    /// <summary>
    /// Encodes an int40 value in packed format.
    /// </summary>
    /// <param name="value">The long value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int40(long value)
        => AddElement(new AbiTypes.Long(value, 5));

    /// <summary>
    /// Encodes a uint40 value in packed format.
    /// </summary>
    /// <param name="value">The ulong value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt40(ulong value)
        => AddElement(new AbiTypes.ULong(value, 5));

    /// <summary>
    /// Encodes an int48 value in packed format.
    /// </summary>
    /// <param name="value">The long value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int48(long value)
        => AddElement(new AbiTypes.Long(value, 6));

    /// <summary>
    /// Encodes a uint48 value in packed format.
    /// </summary>
    /// <param name="value">The ulong value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt48(ulong value)
        => AddElement(new AbiTypes.ULong(value, 6));

    /// <summary>
    /// Encodes an int56 value in packed format.
    /// </summary>
    /// <param name="value">The long value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int56(long value)
        => AddElement(new AbiTypes.Long(value, 7));

    /// <summary>
    /// Encodes a uint56 value in packed format.
    /// </summary>
    /// <param name="value">The ulong value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt56(ulong value)
        => AddElement(new AbiTypes.ULong(value, 7));

    /// <summary>
    /// Encodes an int64 value in packed format.
    /// </summary>
    /// <param name="value">The long value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int64(long value)
        => AddElement(new AbiTypes.Long(value, 8));

    /// <summary>
    /// Encodes a uint64 value in packed format.
    /// </summary>
    /// <param name="value">The ulong value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt64(ulong value)
        => AddElement(new AbiTypes.ULong(value, 8));


    /// <summary>
    /// Encodes an int72 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int72(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 9));

    /// <summary>
    /// Encodes a uint72 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt72(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 9));

    /// <summary>
    /// Encodes an int80 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int80(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 10));

    /// <summary>
    /// Encodes a uint80 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt80(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 10));

    /// <summary>
    /// Encodes an int88 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int88(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 11));

    /// <summary>
    /// Encodes a uint88 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt88(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 11));

    /// <summary>
    /// Encodes an int96 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int96(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 12));

    /// <summary>
    /// Encodes a uint96 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt96(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 12));

    /// <summary>
    /// Encodes an int104 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int104(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 13));

    /// <summary>
    /// Encodes a uint104 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt104(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 13));

    /// <summary>
    /// Encodes an int112 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int112(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 14));

    /// <summary>
    /// Encodes a uint112 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt112(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 14));

    /// <summary>
    /// Encodes an int120 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int120(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 15));

    /// <summary>
    /// Encodes a uint120 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt120(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 15));

    /// <summary>
    /// Encodes an int128 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int128(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 16));

    /// <summary>
    /// Encodes a uint128 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt128(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 16));

    /// <summary>
    /// Encodes an int136 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int136(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 17));

    /// <summary>
    /// Encodes a uint136 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt136(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 17));

    /// <summary>
    /// Encodes an int144 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int144(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 18));

    /// <summary>
    /// Encodes a uint144 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt144(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 18));

    /// <summary>
    /// Encodes an int152 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int152(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 19));

    /// <summary>
    /// Encodes a uint152 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt152(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 19));

    /// <summary>
    /// Encodes an int160 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int160(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 20));

    /// <summary>
    /// Encodes a uint160 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt160(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 20));

    /// <summary>
    /// Encodes an int168 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int168(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 21));

    /// <summary>
    /// Encodes a uint168 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt168(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 21));

    /// <summary>
    /// Encodes an int176 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int176(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 22));

    /// <summary>
    /// Encodes a uint176 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt176(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 22));

    /// <summary>
    /// Encodes an int184 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int184(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 23));

    /// <summary>
    /// Encodes a uint184 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt184(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 23));

    /// <summary>
    /// Encodes an int192 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int192(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 24));

    /// <summary>
    /// Encodes a uint192 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt192(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 24));

    /// <summary>
    /// Encodes an int200 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int200(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 25));

    /// <summary>
    /// Encodes a uint200 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt200(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 25));

    /// <summary>
    /// Encodes an int208 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int208(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 26));

    /// <summary>
    /// Encodes a uint208 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt208(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 26));

    /// <summary>
    /// Encodes an int216 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int216(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 27));

    /// <summary>
    /// Encodes a uint216 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt216(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 27));

    /// <summary>
    /// Encodes an int224 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int224(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 28));

    /// <summary>
    /// Encodes a uint224 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt224(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 28));

    /// <summary>
    /// Encodes an int232 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int232(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 29));

    /// <summary>
    /// Encodes a uint232 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt232(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 29));

    /// <summary>
    /// Encodes an int240 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int240(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 30));

    /// <summary>
    /// Encodes a uint240 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt240(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 30));

    /// <summary>
    /// Encodes an int248 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int248(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 31));

    /// <summary>
    /// Encodes a uint248 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt248(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 31));

    /// <summary>
    /// Encodes an int256 value in packed format.
    /// </summary>
    /// <param name="value">The Int256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder Int256(Int256 value)
        => AddElement(new AbiTypes.Int256(value, 32));

    /// <summary>
    /// Encodes a uint256 value in packed format.
    /// </summary>
    /// <param name="value">The UInt256 value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public PackedAbiEncoder UInt256(UInt256 value)
        => AddElement(new AbiTypes.UInt256(value, 32));

}
