// <auto-generated/>
using EtherSharp.ABI.Types;
using EtherSharp.ABI.Encode.Interfaces;
using EtherSharp.Types;

namespace EtherSharp.ABI;

public partial class AbiEncoder
{
    /// <summary>
    /// Encodes a bytes1 value.
    /// </summary>
    /// <param name="value">The 1-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes1(Bytes1 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes1>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes1(Bytes1 value)
        => Bytes1(value);    
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes1(Bytes1 value)
        => Bytes1(value);
    /// <summary>
    /// Encodes a bytes2 value.
    /// </summary>
    /// <param name="value">The 2-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes2(Bytes2 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes2>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes2(Bytes2 value)
        => Bytes2(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes2(Bytes2 value)
        => Bytes2(value);
    /// <summary>
    /// Encodes a bytes3 value.
    /// </summary>
    /// <param name="value">The 3-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes3(Bytes3 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes3>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes3(Bytes3 value)
        => Bytes3(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes3(Bytes3 value)
        => Bytes3(value);
    /// <summary>
    /// Encodes a bytes4 value.
    /// </summary>
    /// <param name="value">The 4-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes4(Bytes4 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes4>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes4(Bytes4 value)
        => Bytes4(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes4(Bytes4 value)
        => Bytes4(value);
    /// <summary>
    /// Encodes a bytes5 value.
    /// </summary>
    /// <param name="value">The 5-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes5(Bytes5 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes5>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes5(Bytes5 value)
        => Bytes5(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes5(Bytes5 value)
        => Bytes5(value);
    /// <summary>
    /// Encodes a bytes6 value.
    /// </summary>
    /// <param name="value">The 6-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes6(Bytes6 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes6>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes6(Bytes6 value)
        => Bytes6(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes6(Bytes6 value)
        => Bytes6(value);
    /// <summary>
    /// Encodes a bytes7 value.
    /// </summary>
    /// <param name="value">The 7-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes7(Bytes7 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes7>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes7(Bytes7 value)
        => Bytes7(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes7(Bytes7 value)
        => Bytes7(value);
    /// <summary>
    /// Encodes a bytes8 value.
    /// </summary>
    /// <param name="value">The 8-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes8(Bytes8 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes8>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes8(Bytes8 value)
        => Bytes8(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes8(Bytes8 value)
        => Bytes8(value);
    /// <summary>
    /// Encodes a bytes9 value.
    /// </summary>
    /// <param name="value">The 9-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes9(Bytes9 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes9>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes9(Bytes9 value)
        => Bytes9(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes9(Bytes9 value)
        => Bytes9(value);
    /// <summary>
    /// Encodes a bytes10 value.
    /// </summary>
    /// <param name="value">The 10-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes10(Bytes10 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes10>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes10(Bytes10 value)
        => Bytes10(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes10(Bytes10 value)
        => Bytes10(value);
    /// <summary>
    /// Encodes a bytes11 value.
    /// </summary>
    /// <param name="value">The 11-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes11(Bytes11 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes11>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes11(Bytes11 value)
        => Bytes11(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes11(Bytes11 value)
        => Bytes11(value);
    /// <summary>
    /// Encodes a bytes12 value.
    /// </summary>
    /// <param name="value">The 12-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes12(Bytes12 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes12>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes12(Bytes12 value)
        => Bytes12(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes12(Bytes12 value)
        => Bytes12(value);
    /// <summary>
    /// Encodes a bytes13 value.
    /// </summary>
    /// <param name="value">The 13-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes13(Bytes13 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes13>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes13(Bytes13 value)
        => Bytes13(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes13(Bytes13 value)
        => Bytes13(value);
    /// <summary>
    /// Encodes a bytes14 value.
    /// </summary>
    /// <param name="value">The 14-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes14(Bytes14 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes14>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes14(Bytes14 value)
        => Bytes14(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes14(Bytes14 value)
        => Bytes14(value);
    /// <summary>
    /// Encodes a bytes15 value.
    /// </summary>
    /// <param name="value">The 15-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes15(Bytes15 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes15>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes15(Bytes15 value)
        => Bytes15(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes15(Bytes15 value)
        => Bytes15(value);
    /// <summary>
    /// Encodes a bytes16 value.
    /// </summary>
    /// <param name="value">The 16-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes16(Bytes16 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes16>(value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes16(Bytes16 value)
        => Bytes16(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes16(Bytes16 value)
        => Bytes16(value);
    /// <summary>
    /// Encodes a bytes17 value.
    /// </summary>
    /// <param name="value">The 17-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes17(in Bytes17 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes17>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes17(in Bytes17 value)
        => Bytes17(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes17(in Bytes17 value)
        => Bytes17(in value);
    /// <summary>
    /// Encodes a bytes18 value.
    /// </summary>
    /// <param name="value">The 18-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes18(in Bytes18 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes18>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes18(in Bytes18 value)
        => Bytes18(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes18(in Bytes18 value)
        => Bytes18(in value);
    /// <summary>
    /// Encodes a bytes19 value.
    /// </summary>
    /// <param name="value">The 19-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes19(in Bytes19 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes19>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes19(in Bytes19 value)
        => Bytes19(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes19(in Bytes19 value)
        => Bytes19(in value);
    /// <summary>
    /// Encodes a bytes20 value.
    /// </summary>
    /// <param name="value">The 20-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes20(in Bytes20 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes20>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes20(in Bytes20 value)
        => Bytes20(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes20(in Bytes20 value)
        => Bytes20(in value);
    /// <summary>
    /// Encodes a bytes21 value.
    /// </summary>
    /// <param name="value">The 21-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes21(in Bytes21 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes21>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes21(in Bytes21 value)
        => Bytes21(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes21(in Bytes21 value)
        => Bytes21(in value);
    /// <summary>
    /// Encodes a bytes22 value.
    /// </summary>
    /// <param name="value">The 22-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes22(in Bytes22 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes22>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes22(in Bytes22 value)
        => Bytes22(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes22(in Bytes22 value)
        => Bytes22(in value);
    /// <summary>
    /// Encodes a bytes23 value.
    /// </summary>
    /// <param name="value">The 23-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes23(in Bytes23 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes23>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes23(in Bytes23 value)
        => Bytes23(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes23(in Bytes23 value)
        => Bytes23(in value);
    /// <summary>
    /// Encodes a bytes24 value.
    /// </summary>
    /// <param name="value">The 24-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes24(in Bytes24 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes24>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes24(in Bytes24 value)
        => Bytes24(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes24(in Bytes24 value)
        => Bytes24(in value);
    /// <summary>
    /// Encodes a bytes25 value.
    /// </summary>
    /// <param name="value">The 25-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes25(in Bytes25 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes25>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes25(in Bytes25 value)
        => Bytes25(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes25(in Bytes25 value)
        => Bytes25(in value);
    /// <summary>
    /// Encodes a bytes26 value.
    /// </summary>
    /// <param name="value">The 26-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes26(in Bytes26 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes26>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes26(in Bytes26 value)
        => Bytes26(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes26(in Bytes26 value)
        => Bytes26(in value);
    /// <summary>
    /// Encodes a bytes27 value.
    /// </summary>
    /// <param name="value">The 27-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes27(in Bytes27 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes27>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes27(in Bytes27 value)
        => Bytes27(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes27(in Bytes27 value)
        => Bytes27(in value);
    /// <summary>
    /// Encodes a bytes28 value.
    /// </summary>
    /// <param name="value">The 28-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes28(in Bytes28 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes28>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes28(in Bytes28 value)
        => Bytes28(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes28(in Bytes28 value)
        => Bytes28(in value);
    /// <summary>
    /// Encodes a bytes29 value.
    /// </summary>
    /// <param name="value">The 29-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes29(in Bytes29 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes29>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes29(in Bytes29 value)
        => Bytes29(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes29(in Bytes29 value)
        => Bytes29(in value);
    /// <summary>
    /// Encodes a bytes30 value.
    /// </summary>
    /// <param name="value">The 30-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes30(in Bytes30 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes30>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes30(in Bytes30 value)
        => Bytes30(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes30(in Bytes30 value)
        => Bytes30(in value);
    /// <summary>
    /// Encodes a bytes31 value.
    /// </summary>
    /// <param name="value">The 31-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes31(in Bytes31 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes31>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes31(in Bytes31 value)
        => Bytes31(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes31(in Bytes31 value)
        => Bytes31(in value);
    /// <summary>
    /// Encodes a bytes32 value.
    /// </summary>
    /// <param name="value">The 32-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes32(in Bytes32 value)
        => AddElement(new AbiTypes.SizedBytes<Bytes32>(in value));
    IFixedTupleEncoder IFixedTupleEncoder.Bytes32(in Bytes32 value)
        => Bytes32(in value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes32(in Bytes32 value)
        => Bytes32(in value);

}
