// <auto-generated/>
using EtherSharp.ABI.Encode.Interfaces;
using EtherSharp.ABI.Types;
using EtherSharp.Types;

namespace EtherSharp.ABI;

public partial class AbiEncoder
{
    /// <summary>
    /// Encodes a bytes1 array value.
    /// </summary>
    /// <param name="value">The array of 1-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes1Array(params Bytes1[] value)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes1>(value));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes1Array(params Bytes1[] value)
        => Bytes1Array(value);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes1Array(params Bytes1[] value)
        => Bytes1Array(value);
    /// <summary>
    /// Encodes a bytes2 array value.
    /// </summary>
    /// <param name="values">The array of 2-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes2Array(params Bytes2[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes2>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes2Array(params Bytes2[] values)
        => Bytes2Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes2Array(params Bytes2[] values)
        => Bytes2Array(values);
    /// <summary>
    /// Encodes a bytes3 array value.
    /// </summary>
    /// <param name="values">The array of 3-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes3Array(params Bytes3[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes3>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes3Array(params Bytes3[] values)
        => Bytes3Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes3Array(params Bytes3[] values)
        => Bytes3Array(values);
    /// <summary>
    /// Encodes a bytes4 array value.
    /// </summary>
    /// <param name="values">The array of 4-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes4Array(params Bytes4[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes4>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes4Array(params Bytes4[] values)
        => Bytes4Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes4Array(params Bytes4[] values)
        => Bytes4Array(values);
    /// <summary>
    /// Encodes a bytes5 array value.
    /// </summary>
    /// <param name="values">The array of 5-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes5Array(params Bytes5[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes5>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes5Array(params Bytes5[] values)
        => Bytes5Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes5Array(params Bytes5[] values)
        => Bytes5Array(values);
    /// <summary>
    /// Encodes a bytes6 array value.
    /// </summary>
    /// <param name="values">The array of 6-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes6Array(params Bytes6[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes6>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes6Array(params Bytes6[] values)
        => Bytes6Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes6Array(params Bytes6[] values)
        => Bytes6Array(values);
    /// <summary>
    /// Encodes a bytes7 array value.
    /// </summary>
    /// <param name="values">The array of 7-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes7Array(params Bytes7[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes7>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes7Array(params Bytes7[] values)
        => Bytes7Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes7Array(params Bytes7[] values)
        => Bytes7Array(values);
    /// <summary>
    /// Encodes a bytes8 array value.
    /// </summary>
    /// <param name="values">The array of 8-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes8Array(params Bytes8[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes8>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes8Array(params Bytes8[] values)
        => Bytes8Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes8Array(params Bytes8[] values)
        => Bytes8Array(values);
    /// <summary>
    /// Encodes a bytes9 array value.
    /// </summary>
    /// <param name="values">The array of 9-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes9Array(params Bytes9[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes9>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes9Array(params Bytes9[] values)
        => Bytes9Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes9Array(params Bytes9[] values)
        => Bytes9Array(values);
    /// <summary>
    /// Encodes a bytes10 array value.
    /// </summary>
    /// <param name="values">The array of 10-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes10Array(params Bytes10[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes10>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes10Array(params Bytes10[] values)
        => Bytes10Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes10Array(params Bytes10[] values)
        => Bytes10Array(values);
    /// <summary>
    /// Encodes a bytes11 array value.
    /// </summary>
    /// <param name="values">The array of 11-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes11Array(params Bytes11[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes11>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes11Array(params Bytes11[] values)
        => Bytes11Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes11Array(params Bytes11[] values)
        => Bytes11Array(values);
    /// <summary>
    /// Encodes a bytes12 array value.
    /// </summary>
    /// <param name="values">The array of 12-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes12Array(params Bytes12[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes12>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes12Array(params Bytes12[] values)
        => Bytes12Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes12Array(params Bytes12[] values)
        => Bytes12Array(values);
    /// <summary>
    /// Encodes a bytes13 array value.
    /// </summary>
    /// <param name="values">The array of 13-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes13Array(params Bytes13[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes13>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes13Array(params Bytes13[] values)
        => Bytes13Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes13Array(params Bytes13[] values)
        => Bytes13Array(values);
    /// <summary>
    /// Encodes a bytes14 array value.
    /// </summary>
    /// <param name="values">The array of 14-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes14Array(params Bytes14[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes14>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes14Array(params Bytes14[] values)
        => Bytes14Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes14Array(params Bytes14[] values)
        => Bytes14Array(values);
    /// <summary>
    /// Encodes a bytes15 array value.
    /// </summary>
    /// <param name="values">The array of 15-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes15Array(params Bytes15[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes15>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes15Array(params Bytes15[] values)
        => Bytes15Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes15Array(params Bytes15[] values)
        => Bytes15Array(values);
    /// <summary>
    /// Encodes a bytes16 array value.
    /// </summary>
    /// <param name="values">The array of 16-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes16Array(params Bytes16[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes16>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes16Array(params Bytes16[] values)
        => Bytes16Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes16Array(params Bytes16[] values)
        => Bytes16Array(values);
    /// <summary>
    /// Encodes a bytes17 array value.
    /// </summary>
    /// <param name="values">The array of 17-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes17Array(params Bytes17[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes17>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes17Array(params Bytes17[] values)
        => Bytes17Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes17Array(params Bytes17[] values)
        => Bytes17Array(values);
    /// <summary>
    /// Encodes a bytes18 array value.
    /// </summary>
    /// <param name="values">The array of 18-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes18Array(params Bytes18[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes18>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes18Array(params Bytes18[] values)
        => Bytes18Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes18Array(params Bytes18[] values)
        => Bytes18Array(values);
    /// <summary>
    /// Encodes a bytes19 array value.
    /// </summary>
    /// <param name="values">The array of 19-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes19Array(params Bytes19[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes19>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes19Array(params Bytes19[] values)
        => Bytes19Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes19Array(params Bytes19[] values)
        => Bytes19Array(values);
    /// <summary>
    /// Encodes a bytes20 array value.
    /// </summary>
    /// <param name="values">The array of 20-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes20Array(params Bytes20[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes20>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes20Array(params Bytes20[] values)
        => Bytes20Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes20Array(params Bytes20[] values)
        => Bytes20Array(values);
    /// <summary>
    /// Encodes a bytes21 array value.
    /// </summary>
    /// <param name="values">The array of 21-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes21Array(params Bytes21[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes21>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes21Array(params Bytes21[] values)
        => Bytes21Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes21Array(params Bytes21[] values)
        => Bytes21Array(values);
    /// <summary>
    /// Encodes a bytes22 array value.
    /// </summary>
    /// <param name="values">The array of 22-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes22Array(params Bytes22[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes22>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes22Array(params Bytes22[] values)
        => Bytes22Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes22Array(params Bytes22[] values)
        => Bytes22Array(values);
    /// <summary>
    /// Encodes a bytes23 array value.
    /// </summary>
    /// <param name="values">The array of 23-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes23Array(params Bytes23[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes23>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes23Array(params Bytes23[] values)
        => Bytes23Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes23Array(params Bytes23[] values)
        => Bytes23Array(values);
    /// <summary>
    /// Encodes a bytes24 array value.
    /// </summary>
    /// <param name="values">The array of 24-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes24Array(params Bytes24[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes24>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes24Array(params Bytes24[] values)
        => Bytes24Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes24Array(params Bytes24[] values)
        => Bytes24Array(values);
    /// <summary>
    /// Encodes a bytes25 array value.
    /// </summary>
    /// <param name="values">The array of 25-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes25Array(params Bytes25[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes25>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes25Array(params Bytes25[] values)
        => Bytes25Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes25Array(params Bytes25[] values)
        => Bytes25Array(values);
    /// <summary>
    /// Encodes a bytes26 array value.
    /// </summary>
    /// <param name="values">The array of 26-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes26Array(params Bytes26[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes26>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes26Array(params Bytes26[] values)
        => Bytes26Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes26Array(params Bytes26[] values)
        => Bytes26Array(values);
    /// <summary>
    /// Encodes a bytes27 array value.
    /// </summary>
    /// <param name="values">The array of 27-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes27Array(params Bytes27[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes27>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes27Array(params Bytes27[] values)
        => Bytes27Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes27Array(params Bytes27[] values)
        => Bytes27Array(values);
    /// <summary>
    /// Encodes a bytes28 array value.
    /// </summary>
    /// <param name="values">The array of 28-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes28Array(params Bytes28[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes28>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes28Array(params Bytes28[] values)
        => Bytes28Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes28Array(params Bytes28[] values)
        => Bytes28Array(values);
    /// <summary>
    /// Encodes a bytes29 array value.
    /// </summary>
    /// <param name="values">The array of 29-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes29Array(params Bytes29[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes29>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes29Array(params Bytes29[] values)
        => Bytes29Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes29Array(params Bytes29[] values)
        => Bytes29Array(values);
    /// <summary>
    /// Encodes a bytes30 array value.
    /// </summary>
    /// <param name="values">The array of 30-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes30Array(params Bytes30[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes30>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes30Array(params Bytes30[] values)
        => Bytes30Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes30Array(params Bytes30[] values)
        => Bytes30Array(values);
    /// <summary>
    /// Encodes a bytes31 array value.
    /// </summary>
    /// <param name="values">The array of 31-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes31Array(params Bytes31[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes31>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes31Array(params Bytes31[] values)
        => Bytes31Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes31Array(params Bytes31[] values)
        => Bytes31Array(values);
    /// <summary>
    /// Encodes a bytes32 array value.
    /// </summary>
    /// <param name="values">The array of 32-byte values to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public AbiEncoder Bytes32Array(params Bytes32[] values)
        => AddElement(new AbiTypes.SizedBytesArray<Bytes32>(values));
    IArrayAbiEncoder IArrayAbiEncoder.Bytes32Array(params Bytes32[] values)
        => Bytes32Array(values);
    IDynamicTupleEncoder IDynamicTupleEncoder.Bytes32Array(params Bytes32[] values)
        => Bytes32Array(values);

}
