// <auto-generated/>
using EtherSharp.Types;

namespace EtherSharp.ABI.Decode.Interfaces;

public partial interface IDynamicTupleDecoder
{
    /// <summary>
    /// Reads a bytes1 array from the input.
    /// </summary>
    /// <returns>The decoded byte array.</returns>
    public Bytes1[] Bytes1Array();
    /// <summary>
    /// Reads a bytes2 array from the input.
    /// </summary>
    /// <returns>The decoded array of 2-byte values.</returns>
    public Bytes2[] Bytes2Array();
    /// <summary>
    /// Reads a bytes3 array from the input.
    /// </summary>
    /// <returns>The decoded array of 3-byte values.</returns>
    public Bytes3[] Bytes3Array();
    /// <summary>
    /// Reads a bytes4 array from the input.
    /// </summary>
    /// <returns>The decoded array of 4-byte values.</returns>
    public Bytes4[] Bytes4Array();
    /// <summary>
    /// Reads a bytes5 array from the input.
    /// </summary>
    /// <returns>The decoded array of 5-byte values.</returns>
    public Bytes5[] Bytes5Array();
    /// <summary>
    /// Reads a bytes6 array from the input.
    /// </summary>
    /// <returns>The decoded array of 6-byte values.</returns>
    public Bytes6[] Bytes6Array();
    /// <summary>
    /// Reads a bytes7 array from the input.
    /// </summary>
    /// <returns>The decoded array of 7-byte values.</returns>
    public Bytes7[] Bytes7Array();
    /// <summary>
    /// Reads a bytes8 array from the input.
    /// </summary>
    /// <returns>The decoded array of 8-byte values.</returns>
    public Bytes8[] Bytes8Array();
    /// <summary>
    /// Reads a bytes9 array from the input.
    /// </summary>
    /// <returns>The decoded array of 9-byte values.</returns>
    public Bytes9[] Bytes9Array();
    /// <summary>
    /// Reads a bytes10 array from the input.
    /// </summary>
    /// <returns>The decoded array of 10-byte values.</returns>
    public Bytes10[] Bytes10Array();
    /// <summary>
    /// Reads a bytes11 array from the input.
    /// </summary>
    /// <returns>The decoded array of 11-byte values.</returns>
    public Bytes11[] Bytes11Array();
    /// <summary>
    /// Reads a bytes12 array from the input.
    /// </summary>
    /// <returns>The decoded array of 12-byte values.</returns>
    public Bytes12[] Bytes12Array();
    /// <summary>
    /// Reads a bytes13 array from the input.
    /// </summary>
    /// <returns>The decoded array of 13-byte values.</returns>
    public Bytes13[] Bytes13Array();
    /// <summary>
    /// Reads a bytes14 array from the input.
    /// </summary>
    /// <returns>The decoded array of 14-byte values.</returns>
    public Bytes14[] Bytes14Array();
    /// <summary>
    /// Reads a bytes15 array from the input.
    /// </summary>
    /// <returns>The decoded array of 15-byte values.</returns>
    public Bytes15[] Bytes15Array();
    /// <summary>
    /// Reads a bytes16 array from the input.
    /// </summary>
    /// <returns>The decoded array of 16-byte values.</returns>
    public Bytes16[] Bytes16Array();
    /// <summary>
    /// Reads a bytes17 array from the input.
    /// </summary>
    /// <returns>The decoded array of 17-byte values.</returns>
    public Bytes17[] Bytes17Array();
    /// <summary>
    /// Reads a bytes18 array from the input.
    /// </summary>
    /// <returns>The decoded array of 18-byte values.</returns>
    public Bytes18[] Bytes18Array();
    /// <summary>
    /// Reads a bytes19 array from the input.
    /// </summary>
    /// <returns>The decoded array of 19-byte values.</returns>
    public Bytes19[] Bytes19Array();
    /// <summary>
    /// Reads a bytes20 array from the input.
    /// </summary>
    /// <returns>The decoded array of 20-byte values.</returns>
    public Bytes20[] Bytes20Array();
    /// <summary>
    /// Reads a bytes21 array from the input.
    /// </summary>
    /// <returns>The decoded array of 21-byte values.</returns>
    public Bytes21[] Bytes21Array();
    /// <summary>
    /// Reads a bytes22 array from the input.
    /// </summary>
    /// <returns>The decoded array of 22-byte values.</returns>
    public Bytes22[] Bytes22Array();
    /// <summary>
    /// Reads a bytes23 array from the input.
    /// </summary>
    /// <returns>The decoded array of 23-byte values.</returns>
    public Bytes23[] Bytes23Array();
    /// <summary>
    /// Reads a bytes24 array from the input.
    /// </summary>
    /// <returns>The decoded array of 24-byte values.</returns>
    public Bytes24[] Bytes24Array();
    /// <summary>
    /// Reads a bytes25 array from the input.
    /// </summary>
    /// <returns>The decoded array of 25-byte values.</returns>
    public Bytes25[] Bytes25Array();
    /// <summary>
    /// Reads a bytes26 array from the input.
    /// </summary>
    /// <returns>The decoded array of 26-byte values.</returns>
    public Bytes26[] Bytes26Array();
    /// <summary>
    /// Reads a bytes27 array from the input.
    /// </summary>
    /// <returns>The decoded array of 27-byte values.</returns>
    public Bytes27[] Bytes27Array();
    /// <summary>
    /// Reads a bytes28 array from the input.
    /// </summary>
    /// <returns>The decoded array of 28-byte values.</returns>
    public Bytes28[] Bytes28Array();
    /// <summary>
    /// Reads a bytes29 array from the input.
    /// </summary>
    /// <returns>The decoded array of 29-byte values.</returns>
    public Bytes29[] Bytes29Array();
    /// <summary>
    /// Reads a bytes30 array from the input.
    /// </summary>
    /// <returns>The decoded array of 30-byte values.</returns>
    public Bytes30[] Bytes30Array();
    /// <summary>
    /// Reads a bytes31 array from the input.
    /// </summary>
    /// <returns>The decoded array of 31-byte values.</returns>
    public Bytes31[] Bytes31Array();
    /// <summary>
    /// Reads a bytes32 array from the input.
    /// </summary>
    /// <returns>The decoded array of 32-byte values.</returns>
    public Bytes32[] Bytes32Array();
}
