// <auto-generated/>
using EtherSharp.Types;

namespace EtherSharp.ABI.Decode.Interfaces;

public partial interface IDynamicTupleDecoder
{
    /// <summary>
    /// Reads a bytes1 value from the input.
    /// </summary>
    /// <returns>The decoded byte value.</returns>
    public Bytes1 Bytes1();
    /// <summary>
    /// Reads a bytes2 value from the input.
    /// </summary>
    /// <returns>The decoded 2-byte value.</returns>
    public Bytes2 Bytes2();
    /// <summary>
    /// Reads a bytes3 value from the input.
    /// </summary>
    /// <returns>The decoded 3-byte value.</returns>
    public Bytes3 Bytes3();
    /// <summary>
    /// Reads a bytes4 value from the input.
    /// </summary>
    /// <returns>The decoded 4-byte value.</returns>
    public Bytes4 Bytes4();
    /// <summary>
    /// Reads a bytes5 value from the input.
    /// </summary>
    /// <returns>The decoded 5-byte value.</returns>
    public Bytes5 Bytes5();
    /// <summary>
    /// Reads a bytes6 value from the input.
    /// </summary>
    /// <returns>The decoded 6-byte value.</returns>
    public Bytes6 Bytes6();
    /// <summary>
    /// Reads a bytes7 value from the input.
    /// </summary>
    /// <returns>The decoded 7-byte value.</returns>
    public Bytes7 Bytes7();
    /// <summary>
    /// Reads a bytes8 value from the input.
    /// </summary>
    /// <returns>The decoded 8-byte value.</returns>
    public Bytes8 Bytes8();
    /// <summary>
    /// Reads a bytes9 value from the input.
    /// </summary>
    /// <returns>The decoded 9-byte value.</returns>
    public Bytes9 Bytes9();
    /// <summary>
    /// Reads a bytes10 value from the input.
    /// </summary>
    /// <returns>The decoded 10-byte value.</returns>
    public Bytes10 Bytes10();
    /// <summary>
    /// Reads a bytes11 value from the input.
    /// </summary>
    /// <returns>The decoded 11-byte value.</returns>
    public Bytes11 Bytes11();
    /// <summary>
    /// Reads a bytes12 value from the input.
    /// </summary>
    /// <returns>The decoded 12-byte value.</returns>
    public Bytes12 Bytes12();
    /// <summary>
    /// Reads a bytes13 value from the input.
    /// </summary>
    /// <returns>The decoded 13-byte value.</returns>
    public Bytes13 Bytes13();
    /// <summary>
    /// Reads a bytes14 value from the input.
    /// </summary>
    /// <returns>The decoded 14-byte value.</returns>
    public Bytes14 Bytes14();
    /// <summary>
    /// Reads a bytes15 value from the input.
    /// </summary>
    /// <returns>The decoded 15-byte value.</returns>
    public Bytes15 Bytes15();
    /// <summary>
    /// Reads a bytes16 value from the input.
    /// </summary>
    /// <returns>The decoded 16-byte value.</returns>
    public Bytes16 Bytes16();
    /// <summary>
    /// Reads a bytes17 value from the input.
    /// </summary>
    /// <returns>The decoded 17-byte value.</returns>
    public Bytes17 Bytes17();
    /// <summary>
    /// Reads a bytes18 value from the input.
    /// </summary>
    /// <returns>The decoded 18-byte value.</returns>
    public Bytes18 Bytes18();
    /// <summary>
    /// Reads a bytes19 value from the input.
    /// </summary>
    /// <returns>The decoded 19-byte value.</returns>
    public Bytes19 Bytes19();
    /// <summary>
    /// Reads a bytes20 value from the input.
    /// </summary>
    /// <returns>The decoded 20-byte value.</returns>
    public Bytes20 Bytes20();
    /// <summary>
    /// Reads a bytes21 value from the input.
    /// </summary>
    /// <returns>The decoded 21-byte value.</returns>
    public Bytes21 Bytes21();
    /// <summary>
    /// Reads a bytes22 value from the input.
    /// </summary>
    /// <returns>The decoded 22-byte value.</returns>
    public Bytes22 Bytes22();
    /// <summary>
    /// Reads a bytes23 value from the input.
    /// </summary>
    /// <returns>The decoded 23-byte value.</returns>
    public Bytes23 Bytes23();
    /// <summary>
    /// Reads a bytes24 value from the input.
    /// </summary>
    /// <returns>The decoded 24-byte value.</returns>
    public Bytes24 Bytes24();
    /// <summary>
    /// Reads a bytes25 value from the input.
    /// </summary>
    /// <returns>The decoded 25-byte value.</returns>
    public Bytes25 Bytes25();
    /// <summary>
    /// Reads a bytes26 value from the input.
    /// </summary>
    /// <returns>The decoded 26-byte value.</returns>
    public Bytes26 Bytes26();
    /// <summary>
    /// Reads a bytes27 value from the input.
    /// </summary>
    /// <returns>The decoded 27-byte value.</returns>
    public Bytes27 Bytes27();
    /// <summary>
    /// Reads a bytes28 value from the input.
    /// </summary>
    /// <returns>The decoded 28-byte value.</returns>
    public Bytes28 Bytes28();
    /// <summary>
    /// Reads a bytes29 value from the input.
    /// </summary>
    /// <returns>The decoded 29-byte value.</returns>
    public Bytes29 Bytes29();
    /// <summary>
    /// Reads a bytes30 value from the input.
    /// </summary>
    /// <returns>The decoded 30-byte value.</returns>
    public Bytes30 Bytes30();
    /// <summary>
    /// Reads a bytes31 value from the input.
    /// </summary>
    /// <returns>The decoded 31-byte value.</returns>
    public Bytes31 Bytes31();
    /// <summary>
    /// Reads a bytes32 value from the input.
    /// </summary>
    /// <returns>The decoded 32-byte value.</returns>
    public Bytes32 Bytes32();
}
