// <auto-generated/>

using System.Buffers.Binary;
using System.Numerics;
using System.Runtime.CompilerServices;

namespace EtherSharp.Interpreter.Crypto;

/// <summary>
/// One-shot RIPEMD-160 hashing, using the original specification's two parallel lanes.
/// </summary>
internal static class Ripemd160
{
    public static void HashData(ReadOnlySpan<byte> input, Span<byte> destination)
    {
        if(destination.Length < 20)
        {
            throw new ArgumentException("The destination must contain at least 20 bytes.", nameof(destination));
        }
        destination = destination[..20];

        Span<uint> state = [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0];
        Span<byte> padding = stackalloc byte[64];
        ulong bitLength = (ulong) input.Length * 8;

        while(input.Length >= 64)
        {
            Compress(input[..64], state);
            input = input[64..];
        }

        // Append the set bit and little-endian length, using a second block when necessary.
        padding.Clear();
        // The remainder is less than one block; copy words without a general-purpose memmove call.
        int offset = 0;
        for(; offset <= input.Length - 8; offset += 8)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(padding[offset..], BinaryPrimitives.ReadUInt64LittleEndian(input[offset..]));
        }
        for(; offset < input.Length; offset++)
        {
            padding[offset] = input[offset];
        }
        padding[input.Length] = 0x80;
        if(input.Length >= 56)
        {
            Compress(padding, state);
            padding.Clear();
        }
        BinaryPrimitives.WriteUInt64LittleEndian(padding[56..], bitLength);
        Compress(padding, state);

        BinaryPrimitives.WriteUInt32LittleEndian(destination[0..], state[0]);
        BinaryPrimitives.WriteUInt32LittleEndian(destination[4..], state[1]);
        BinaryPrimitives.WriteUInt32LittleEndian(destination[8..], state[2]);
        BinaryPrimitives.WriteUInt32LittleEndian(destination[12..], state[3]);
        BinaryPrimitives.WriteUInt32LittleEndian(destination[16..], state[4]);
    }

    // Avoid running the large unrolled compression method in the minimally optimized JIT tier.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    private static void Compress(ReadOnlySpan<byte> block, Span<uint> state)
    {
        // Compression consumes exactly one block and five chaining words.
        block = block[..64];
        state = state[..5];

        // Named words and unrolled steps expose constant rotations and eliminate round dispatch.
        uint x0 = BinaryPrimitives.ReadUInt32LittleEndian(block[0..]);
        uint x1 = BinaryPrimitives.ReadUInt32LittleEndian(block[4..]);
        uint x2 = BinaryPrimitives.ReadUInt32LittleEndian(block[8..]);
        uint x3 = BinaryPrimitives.ReadUInt32LittleEndian(block[12..]);
        uint x4 = BinaryPrimitives.ReadUInt32LittleEndian(block[16..]);
        uint x5 = BinaryPrimitives.ReadUInt32LittleEndian(block[20..]);
        uint x6 = BinaryPrimitives.ReadUInt32LittleEndian(block[24..]);
        uint x7 = BinaryPrimitives.ReadUInt32LittleEndian(block[28..]);
        uint x8 = BinaryPrimitives.ReadUInt32LittleEndian(block[32..]);
        uint x9 = BinaryPrimitives.ReadUInt32LittleEndian(block[36..]);
        uint x10 = BinaryPrimitives.ReadUInt32LittleEndian(block[40..]);
        uint x11 = BinaryPrimitives.ReadUInt32LittleEndian(block[44..]);
        uint x12 = BinaryPrimitives.ReadUInt32LittleEndian(block[48..]);
        uint x13 = BinaryPrimitives.ReadUInt32LittleEndian(block[52..]);
        uint x14 = BinaryPrimitives.ReadUInt32LittleEndian(block[56..]);
        uint x15 = BinaryPrimitives.ReadUInt32LittleEndian(block[60..]);

        uint a = state[0], b = state[1], c = state[2], d = state[3], e = state[4];
        uint aa = a, bb = b, cc = c, dd = d, ee = e;

        // RIPEMD-160 arithmetic is modulo 2^32, including in checked builds.
        unchecked
        {
            // Round 1: interleave the independent left and right lanes.
            a = BitOperations.RotateLeft(a + (b ^ c ^ d) + x0, 11) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ (cc | ~dd)) + x5 + 0x50A28BE6, 8) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ b ^ c) + x1, 14) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ (bb | ~cc)) + x14 + 0x50A28BE6, 9) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ a ^ b) + x2, 15) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ (aa | ~bb)) + x7 + 0x50A28BE6, 9) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ e ^ a) + x3, 12) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ (ee | ~aa)) + x0 + 0x50A28BE6, 11) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ d ^ e) + x4, 5) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ (dd | ~ee)) + x9 + 0x50A28BE6, 13) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ c ^ d) + x5, 8) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ (cc | ~dd)) + x2 + 0x50A28BE6, 15) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ b ^ c) + x6, 7) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ (bb | ~cc)) + x11 + 0x50A28BE6, 15) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ a ^ b) + x7, 9) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ (aa | ~bb)) + x4 + 0x50A28BE6, 5) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ e ^ a) + x8, 11) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ (ee | ~aa)) + x13 + 0x50A28BE6, 7) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ d ^ e) + x9, 13) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ (dd | ~ee)) + x6 + 0x50A28BE6, 7) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ c ^ d) + x10, 14) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ (cc | ~dd)) + x15 + 0x50A28BE6, 8) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ b ^ c) + x11, 15) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ (bb | ~cc)) + x8 + 0x50A28BE6, 11) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ a ^ b) + x12, 6) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ (aa | ~bb)) + x1 + 0x50A28BE6, 14) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ e ^ a) + x13, 7) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ (ee | ~aa)) + x10 + 0x50A28BE6, 14) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ d ^ e) + x14, 9) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ (dd | ~ee)) + x3 + 0x50A28BE6, 12) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ c ^ d) + x15, 8) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ (cc | ~dd)) + x12 + 0x50A28BE6, 6) + ee;
            cc = BitOperations.RotateLeft(cc, 10);

            // Round 2: interleave the independent left and right lanes.
            e = BitOperations.RotateLeft(e + (c ^ (a & (b ^ c))) + x7 + 0x5A827999, 7) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (bb ^ (cc & (aa ^ bb))) + x6 + 0x5C4DD124, 9) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (b ^ (e & (a ^ b))) + x4 + 0x5A827999, 6) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (aa ^ (bb & (ee ^ aa))) + x11 + 0x5C4DD124, 13) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (a ^ (d & (e ^ a))) + x13 + 0x5A827999, 8) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (ee ^ (aa & (dd ^ ee))) + x3 + 0x5C4DD124, 15) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (e ^ (c & (d ^ e))) + x1 + 0x5A827999, 13) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (dd ^ (ee & (cc ^ dd))) + x7 + 0x5C4DD124, 7) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (d ^ (b & (c ^ d))) + x10 + 0x5A827999, 11) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (cc ^ (dd & (bb ^ cc))) + x0 + 0x5C4DD124, 12) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (c ^ (a & (b ^ c))) + x6 + 0x5A827999, 9) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (bb ^ (cc & (aa ^ bb))) + x13 + 0x5C4DD124, 8) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (b ^ (e & (a ^ b))) + x15 + 0x5A827999, 7) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (aa ^ (bb & (ee ^ aa))) + x5 + 0x5C4DD124, 9) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (a ^ (d & (e ^ a))) + x3 + 0x5A827999, 15) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (ee ^ (aa & (dd ^ ee))) + x10 + 0x5C4DD124, 11) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (e ^ (c & (d ^ e))) + x12 + 0x5A827999, 7) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (dd ^ (ee & (cc ^ dd))) + x14 + 0x5C4DD124, 7) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (d ^ (b & (c ^ d))) + x0 + 0x5A827999, 12) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (cc ^ (dd & (bb ^ cc))) + x15 + 0x5C4DD124, 7) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (c ^ (a & (b ^ c))) + x9 + 0x5A827999, 15) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (bb ^ (cc & (aa ^ bb))) + x8 + 0x5C4DD124, 12) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (b ^ (e & (a ^ b))) + x5 + 0x5A827999, 9) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (aa ^ (bb & (ee ^ aa))) + x12 + 0x5C4DD124, 7) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (a ^ (d & (e ^ a))) + x2 + 0x5A827999, 11) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (ee ^ (aa & (dd ^ ee))) + x4 + 0x5C4DD124, 6) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (e ^ (c & (d ^ e))) + x14 + 0x5A827999, 7) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (dd ^ (ee & (cc ^ dd))) + x9 + 0x5C4DD124, 15) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (d ^ (b & (c ^ d))) + x11 + 0x5A827999, 13) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (cc ^ (dd & (bb ^ cc))) + x1 + 0x5C4DD124, 13) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (c ^ (a & (b ^ c))) + x8 + 0x5A827999, 12) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (bb ^ (cc & (aa ^ bb))) + x2 + 0x5C4DD124, 11) + dd;
            bb = BitOperations.RotateLeft(bb, 10);

            // Round 3: interleave the independent left and right lanes.
            d = BitOperations.RotateLeft(d + ((e | ~a) ^ b) + x3 + 0x6ED9EBA1, 11) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + ((ee | ~aa) ^ bb) + x15 + 0x6D703EF3, 9) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + ((d | ~e) ^ a) + x10 + 0x6ED9EBA1, 13) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + ((dd | ~ee) ^ aa) + x5 + 0x6D703EF3, 7) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + ((c | ~d) ^ e) + x14 + 0x6ED9EBA1, 6) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + ((cc | ~dd) ^ ee) + x1 + 0x6D703EF3, 15) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + ((b | ~c) ^ d) + x4 + 0x6ED9EBA1, 7) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + ((bb | ~cc) ^ dd) + x3 + 0x6D703EF3, 11) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + ((a | ~b) ^ c) + x9 + 0x6ED9EBA1, 14) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + ((aa | ~bb) ^ cc) + x7 + 0x6D703EF3, 8) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + ((e | ~a) ^ b) + x15 + 0x6ED9EBA1, 9) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + ((ee | ~aa) ^ bb) + x14 + 0x6D703EF3, 6) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + ((d | ~e) ^ a) + x8 + 0x6ED9EBA1, 13) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + ((dd | ~ee) ^ aa) + x6 + 0x6D703EF3, 6) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + ((c | ~d) ^ e) + x1 + 0x6ED9EBA1, 15) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + ((cc | ~dd) ^ ee) + x9 + 0x6D703EF3, 14) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + ((b | ~c) ^ d) + x2 + 0x6ED9EBA1, 14) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + ((bb | ~cc) ^ dd) + x11 + 0x6D703EF3, 12) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + ((a | ~b) ^ c) + x7 + 0x6ED9EBA1, 8) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + ((aa | ~bb) ^ cc) + x8 + 0x6D703EF3, 13) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + ((e | ~a) ^ b) + x0 + 0x6ED9EBA1, 13) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + ((ee | ~aa) ^ bb) + x12 + 0x6D703EF3, 5) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + ((d | ~e) ^ a) + x6 + 0x6ED9EBA1, 6) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + ((dd | ~ee) ^ aa) + x2 + 0x6D703EF3, 14) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + ((c | ~d) ^ e) + x13 + 0x6ED9EBA1, 5) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + ((cc | ~dd) ^ ee) + x10 + 0x6D703EF3, 13) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + ((b | ~c) ^ d) + x11 + 0x6ED9EBA1, 12) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + ((bb | ~cc) ^ dd) + x0 + 0x6D703EF3, 13) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + ((a | ~b) ^ c) + x5 + 0x6ED9EBA1, 7) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + ((aa | ~bb) ^ cc) + x4 + 0x6D703EF3, 7) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + ((e | ~a) ^ b) + x12 + 0x6ED9EBA1, 5) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + ((ee | ~aa) ^ bb) + x13 + 0x6D703EF3, 5) + cc;
            aa = BitOperations.RotateLeft(aa, 10);

            // Round 4: interleave the independent left and right lanes.
            c = BitOperations.RotateLeft(c + (e ^ (a & (d ^ e))) + x1 + 0x8F1BBCDC, 11) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (aa ^ (dd & (ee ^ aa))) + x8 + 0x7A6D76E9, 15) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (d ^ (e & (c ^ d))) + x9 + 0x8F1BBCDC, 12) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (ee ^ (cc & (dd ^ ee))) + x6 + 0x7A6D76E9, 5) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (c ^ (d & (b ^ c))) + x11 + 0x8F1BBCDC, 14) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (dd ^ (bb & (cc ^ dd))) + x4 + 0x7A6D76E9, 8) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (b ^ (c & (a ^ b))) + x10 + 0x8F1BBCDC, 15) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (cc ^ (aa & (bb ^ cc))) + x1 + 0x7A6D76E9, 11) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (a ^ (b & (e ^ a))) + x0 + 0x8F1BBCDC, 14) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (bb ^ (ee & (aa ^ bb))) + x3 + 0x7A6D76E9, 14) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (e ^ (a & (d ^ e))) + x8 + 0x8F1BBCDC, 15) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (aa ^ (dd & (ee ^ aa))) + x11 + 0x7A6D76E9, 14) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (d ^ (e & (c ^ d))) + x12 + 0x8F1BBCDC, 9) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (ee ^ (cc & (dd ^ ee))) + x15 + 0x7A6D76E9, 6) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (c ^ (d & (b ^ c))) + x4 + 0x8F1BBCDC, 8) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (dd ^ (bb & (cc ^ dd))) + x0 + 0x7A6D76E9, 14) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (b ^ (c & (a ^ b))) + x13 + 0x8F1BBCDC, 9) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (cc ^ (aa & (bb ^ cc))) + x5 + 0x7A6D76E9, 6) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (a ^ (b & (e ^ a))) + x3 + 0x8F1BBCDC, 14) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (bb ^ (ee & (aa ^ bb))) + x12 + 0x7A6D76E9, 9) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (e ^ (a & (d ^ e))) + x7 + 0x8F1BBCDC, 5) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (aa ^ (dd & (ee ^ aa))) + x2 + 0x7A6D76E9, 12) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (d ^ (e & (c ^ d))) + x15 + 0x8F1BBCDC, 6) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (ee ^ (cc & (dd ^ ee))) + x13 + 0x7A6D76E9, 9) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (c ^ (d & (b ^ c))) + x14 + 0x8F1BBCDC, 8) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (dd ^ (bb & (cc ^ dd))) + x9 + 0x7A6D76E9, 12) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (b ^ (c & (a ^ b))) + x5 + 0x8F1BBCDC, 6) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (cc ^ (aa & (bb ^ cc))) + x7 + 0x7A6D76E9, 5) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (a ^ (b & (e ^ a))) + x6 + 0x8F1BBCDC, 5) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (bb ^ (ee & (aa ^ bb))) + x10 + 0x7A6D76E9, 15) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (e ^ (a & (d ^ e))) + x2 + 0x8F1BBCDC, 12) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (aa ^ (dd & (ee ^ aa))) + x14 + 0x7A6D76E9, 8) + bb;
            ee = BitOperations.RotateLeft(ee, 10);

            // Round 5: interleave the independent left and right lanes.
            b = BitOperations.RotateLeft(b + (c ^ (d | ~e)) + x4 + 0xA953FD4E, 9) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ dd ^ ee) + x12, 8) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ (c | ~d)) + x0 + 0xA953FD4E, 15) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ cc ^ dd) + x15, 5) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ (b | ~c)) + x5 + 0xA953FD4E, 5) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ bb ^ cc) + x10, 12) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ (a | ~b)) + x9 + 0xA953FD4E, 11) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ aa ^ bb) + x4, 9) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ (e | ~a)) + x7 + 0xA953FD4E, 6) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ ee ^ aa) + x1, 12) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ (d | ~e)) + x12 + 0xA953FD4E, 8) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ dd ^ ee) + x5, 5) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ (c | ~d)) + x2 + 0xA953FD4E, 13) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ cc ^ dd) + x8, 14) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ (b | ~c)) + x10 + 0xA953FD4E, 12) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ bb ^ cc) + x7, 6) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ (a | ~b)) + x14 + 0xA953FD4E, 5) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ aa ^ bb) + x6, 8) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ (e | ~a)) + x1 + 0xA953FD4E, 12) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ ee ^ aa) + x2, 13) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ (d | ~e)) + x3 + 0xA953FD4E, 13) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ dd ^ ee) + x13, 6) + aa;
            dd = BitOperations.RotateLeft(dd, 10);
            a = BitOperations.RotateLeft(a + (b ^ (c | ~d)) + x8 + 0xA953FD4E, 14) + e;
            c = BitOperations.RotateLeft(c, 10);
            aa = BitOperations.RotateLeft(aa + (bb ^ cc ^ dd) + x14, 5) + ee;
            cc = BitOperations.RotateLeft(cc, 10);
            e = BitOperations.RotateLeft(e + (a ^ (b | ~c)) + x11 + 0xA953FD4E, 11) + d;
            b = BitOperations.RotateLeft(b, 10);
            ee = BitOperations.RotateLeft(ee + (aa ^ bb ^ cc) + x0, 15) + dd;
            bb = BitOperations.RotateLeft(bb, 10);
            d = BitOperations.RotateLeft(d + (e ^ (a | ~b)) + x6 + 0xA953FD4E, 8) + c;
            a = BitOperations.RotateLeft(a, 10);
            dd = BitOperations.RotateLeft(dd + (ee ^ aa ^ bb) + x3, 13) + cc;
            aa = BitOperations.RotateLeft(aa, 10);
            c = BitOperations.RotateLeft(c + (d ^ (e | ~a)) + x15 + 0xA953FD4E, 5) + b;
            e = BitOperations.RotateLeft(e, 10);
            cc = BitOperations.RotateLeft(cc + (dd ^ ee ^ aa) + x9, 11) + bb;
            ee = BitOperations.RotateLeft(ee, 10);
            b = BitOperations.RotateLeft(b + (c ^ (d | ~e)) + x13 + 0xA953FD4E, 6) + a;
            d = BitOperations.RotateLeft(d, 10);
            bb = BitOperations.RotateLeft(bb + (cc ^ dd ^ ee) + x11, 11) + aa;
            dd = BitOperations.RotateLeft(dd, 10);


            // Cross-add both lanes to the previous chaining state.
            uint combined = state[1] + c + dd;
            state[1] = state[2] + d + ee;
            state[2] = state[3] + e + aa;
            state[3] = state[4] + a + bb;
            state[4] = state[0] + b + cc;
            state[0] = combined;
        }
    }
}
