using EtherSharp.Numerics;

namespace EtherSharp.ABI.Encode.Interfaces;
public partial interface IDynamicTupleEncoder 
{
    public IDynamicTupleEncoder Int8(sbyte value);
    public IDynamicTupleEncoder UInt8(byte value);

    public IDynamicTupleEncoder Int16(short value);
    public IDynamicTupleEncoder UInt16(ushort value);

    public IDynamicTupleEncoder Int24(int value);
    public IDynamicTupleEncoder UInt24(uint value);
    public IDynamicTupleEncoder Int32(int value);
    public IDynamicTupleEncoder UInt32(uint value);
    public IDynamicTupleEncoder Int40(long value);
    public IDynamicTupleEncoder UInt40(ulong value);
    public IDynamicTupleEncoder Int48(long value);
    public IDynamicTupleEncoder UInt48(ulong value);
    public IDynamicTupleEncoder Int56(long value);
    public IDynamicTupleEncoder UInt56(ulong value);
    public IDynamicTupleEncoder Int64(long value);
    public IDynamicTupleEncoder UInt64(ulong value);
    public IDynamicTupleEncoder Int72(Int256 value);
    public IDynamicTupleEncoder UInt72(UInt256 value);
    public IDynamicTupleEncoder Int80(Int256 value);
    public IDynamicTupleEncoder UInt80(UInt256 value);
    public IDynamicTupleEncoder Int88(Int256 value);
    public IDynamicTupleEncoder UInt88(UInt256 value);
    public IDynamicTupleEncoder Int96(Int256 value);
    public IDynamicTupleEncoder UInt96(UInt256 value);
    public IDynamicTupleEncoder Int104(Int256 value);
    public IDynamicTupleEncoder UInt104(UInt256 value);
    public IDynamicTupleEncoder Int112(Int256 value);
    public IDynamicTupleEncoder UInt112(UInt256 value);
    public IDynamicTupleEncoder Int120(Int256 value);
    public IDynamicTupleEncoder UInt120(UInt256 value);
    public IDynamicTupleEncoder Int128(Int256 value);
    public IDynamicTupleEncoder UInt128(UInt256 value);
    public IDynamicTupleEncoder Int136(Int256 value);
    public IDynamicTupleEncoder UInt136(UInt256 value);
    public IDynamicTupleEncoder Int144(Int256 value);
    public IDynamicTupleEncoder UInt144(UInt256 value);
    public IDynamicTupleEncoder Int152(Int256 value);
    public IDynamicTupleEncoder UInt152(UInt256 value);
    public IDynamicTupleEncoder Int160(Int256 value);
    public IDynamicTupleEncoder UInt160(UInt256 value);
    public IDynamicTupleEncoder Int168(Int256 value);
    public IDynamicTupleEncoder UInt168(UInt256 value);
    public IDynamicTupleEncoder Int176(Int256 value);
    public IDynamicTupleEncoder UInt176(UInt256 value);
    public IDynamicTupleEncoder Int184(Int256 value);
    public IDynamicTupleEncoder UInt184(UInt256 value);
    public IDynamicTupleEncoder Int192(Int256 value);
    public IDynamicTupleEncoder UInt192(UInt256 value);
    public IDynamicTupleEncoder Int200(Int256 value);
    public IDynamicTupleEncoder UInt200(UInt256 value);
    public IDynamicTupleEncoder Int208(Int256 value);
    public IDynamicTupleEncoder UInt208(UInt256 value);
    public IDynamicTupleEncoder Int216(Int256 value);
    public IDynamicTupleEncoder UInt216(UInt256 value);
    public IDynamicTupleEncoder Int224(Int256 value);
    public IDynamicTupleEncoder UInt224(UInt256 value);
    public IDynamicTupleEncoder Int232(Int256 value);
    public IDynamicTupleEncoder UInt232(UInt256 value);
    public IDynamicTupleEncoder Int240(Int256 value);
    public IDynamicTupleEncoder UInt240(UInt256 value);
    public IDynamicTupleEncoder Int248(Int256 value);
    public IDynamicTupleEncoder UInt248(UInt256 value);
    public IDynamicTupleEncoder Int256(Int256 value);
    public IDynamicTupleEncoder UInt256(UInt256 value);
}