// <auto-generated/>
namespace EtherSharp.ABI.Encode.Interfaces;

public partial interface IFixedTupleEncoder
{
    /// <summary>
    /// Encodes a bytes1 value.
    /// </summary>
    /// <param name="value">The byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes1(byte value);
    /// <summary>
    /// Encodes a bytes2 value.
    /// </summary>
    /// <param name="value">The 2-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes2(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes3 value.
    /// </summary>
    /// <param name="value">The 3-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes3(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes4 value.
    /// </summary>
    /// <param name="value">The 4-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes4(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes5 value.
    /// </summary>
    /// <param name="value">The 5-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes5(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes6 value.
    /// </summary>
    /// <param name="value">The 6-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes6(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes7 value.
    /// </summary>
    /// <param name="value">The 7-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes7(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes8 value.
    /// </summary>
    /// <param name="value">The 8-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes8(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes9 value.
    /// </summary>
    /// <param name="value">The 9-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes9(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes10 value.
    /// </summary>
    /// <param name="value">The 10-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes10(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes11 value.
    /// </summary>
    /// <param name="value">The 11-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes11(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes12 value.
    /// </summary>
    /// <param name="value">The 12-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes12(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes13 value.
    /// </summary>
    /// <param name="value">The 13-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes13(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes14 value.
    /// </summary>
    /// <param name="value">The 14-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes14(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes15 value.
    /// </summary>
    /// <param name="value">The 15-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes15(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes16 value.
    /// </summary>
    /// <param name="value">The 16-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes16(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes17 value.
    /// </summary>
    /// <param name="value">The 17-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes17(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes18 value.
    /// </summary>
    /// <param name="value">The 18-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes18(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes19 value.
    /// </summary>
    /// <param name="value">The 19-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes19(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes20 value.
    /// </summary>
    /// <param name="value">The 20-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes20(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes21 value.
    /// </summary>
    /// <param name="value">The 21-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes21(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes22 value.
    /// </summary>
    /// <param name="value">The 22-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes22(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes23 value.
    /// </summary>
    /// <param name="value">The 23-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes23(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes24 value.
    /// </summary>
    /// <param name="value">The 24-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes24(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes25 value.
    /// </summary>
    /// <param name="value">The 25-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes25(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes26 value.
    /// </summary>
    /// <param name="value">The 26-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes26(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes27 value.
    /// </summary>
    /// <param name="value">The 27-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes27(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes28 value.
    /// </summary>
    /// <param name="value">The 28-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes28(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes29 value.
    /// </summary>
    /// <param name="value">The 29-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes29(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes30 value.
    /// </summary>
    /// <param name="value">The 30-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes30(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes31 value.
    /// </summary>
    /// <param name="value">The 31-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes31(ReadOnlyMemory<byte> value);
    /// <summary>
    /// Encodes a bytes32 value.
    /// </summary>
    /// <param name="value">The 32-byte value to encode.</param>
    /// <returns>This encoder instance for method chaining.</returns>
    public IFixedTupleEncoder Bytes32(ReadOnlyMemory<byte> value);

}
