using EtherSharp.Numerics;

namespace EtherSharp.ABI.Encode.Interfaces;
public partial interface IFixedTupleEncoder 
{
    public IFixedTupleEncoder Int8(sbyte value);
    public IFixedTupleEncoder UInt8(byte value);

    public IFixedTupleEncoder Int16(short value);
    public IFixedTupleEncoder UInt16(ushort value);

    public IFixedTupleEncoder Int24(int value);
    public IFixedTupleEncoder UInt24(uint value);
    public IFixedTupleEncoder Int32(int value);
    public IFixedTupleEncoder UInt32(uint value);
    public IFixedTupleEncoder Int40(long value);
    public IFixedTupleEncoder UInt40(ulong value);
    public IFixedTupleEncoder Int48(long value);
    public IFixedTupleEncoder UInt48(ulong value);
    public IFixedTupleEncoder Int56(long value);
    public IFixedTupleEncoder UInt56(ulong value);
    public IFixedTupleEncoder Int64(long value);
    public IFixedTupleEncoder UInt64(ulong value);
    public IFixedTupleEncoder Int72(Int256 value);
    public IFixedTupleEncoder UInt72(UInt256 value);
    public IFixedTupleEncoder Int80(Int256 value);
    public IFixedTupleEncoder UInt80(UInt256 value);
    public IFixedTupleEncoder Int88(Int256 value);
    public IFixedTupleEncoder UInt88(UInt256 value);
    public IFixedTupleEncoder Int96(Int256 value);
    public IFixedTupleEncoder UInt96(UInt256 value);
    public IFixedTupleEncoder Int104(Int256 value);
    public IFixedTupleEncoder UInt104(UInt256 value);
    public IFixedTupleEncoder Int112(Int256 value);
    public IFixedTupleEncoder UInt112(UInt256 value);
    public IFixedTupleEncoder Int120(Int256 value);
    public IFixedTupleEncoder UInt120(UInt256 value);
    public IFixedTupleEncoder Int128(Int256 value);
    public IFixedTupleEncoder UInt128(UInt256 value);
    public IFixedTupleEncoder Int136(Int256 value);
    public IFixedTupleEncoder UInt136(UInt256 value);
    public IFixedTupleEncoder Int144(Int256 value);
    public IFixedTupleEncoder UInt144(UInt256 value);
    public IFixedTupleEncoder Int152(Int256 value);
    public IFixedTupleEncoder UInt152(UInt256 value);
    public IFixedTupleEncoder Int160(Int256 value);
    public IFixedTupleEncoder UInt160(UInt256 value);
    public IFixedTupleEncoder Int168(Int256 value);
    public IFixedTupleEncoder UInt168(UInt256 value);
    public IFixedTupleEncoder Int176(Int256 value);
    public IFixedTupleEncoder UInt176(UInt256 value);
    public IFixedTupleEncoder Int184(Int256 value);
    public IFixedTupleEncoder UInt184(UInt256 value);
    public IFixedTupleEncoder Int192(Int256 value);
    public IFixedTupleEncoder UInt192(UInt256 value);
    public IFixedTupleEncoder Int200(Int256 value);
    public IFixedTupleEncoder UInt200(UInt256 value);
    public IFixedTupleEncoder Int208(Int256 value);
    public IFixedTupleEncoder UInt208(UInt256 value);
    public IFixedTupleEncoder Int216(Int256 value);
    public IFixedTupleEncoder UInt216(UInt256 value);
    public IFixedTupleEncoder Int224(Int256 value);
    public IFixedTupleEncoder UInt224(UInt256 value);
    public IFixedTupleEncoder Int232(Int256 value);
    public IFixedTupleEncoder UInt232(UInt256 value);
    public IFixedTupleEncoder Int240(Int256 value);
    public IFixedTupleEncoder UInt240(UInt256 value);
    public IFixedTupleEncoder Int248(Int256 value);
    public IFixedTupleEncoder UInt248(UInt256 value);
    public IFixedTupleEncoder Int256(Int256 value);
    public IFixedTupleEncoder UInt256(UInt256 value);
}