using System.Numerics;

namespace EtherSharp.ABI.Encode.Interfaces;
public partial interface IStructAbiEncoder
{
    public IStructAbiEncoder Int8(sbyte value);
    public IStructAbiEncoder UInt8(byte value);

    public IStructAbiEncoder Int16(short value);
    public IStructAbiEncoder UInt16(ushort value);

    public IStructAbiEncoder Int24(int value);
    public IStructAbiEncoder UInt24(uint value);
    public IStructAbiEncoder Int32(int value);
    public IStructAbiEncoder UInt32(uint value);
    public IStructAbiEncoder Int40(long value);
    public IStructAbiEncoder UInt40(ulong value);
    public IStructAbiEncoder Int48(long value);
    public IStructAbiEncoder UInt48(ulong value);
    public IStructAbiEncoder Int56(long value);
    public IStructAbiEncoder UInt56(ulong value);
    public IStructAbiEncoder Int64(long value);
    public IStructAbiEncoder UInt64(ulong value);
    public IStructAbiEncoder Int72(BigInteger value);
    public IStructAbiEncoder UInt72(BigInteger value);
    public IStructAbiEncoder Int80(BigInteger value);
    public IStructAbiEncoder UInt80(BigInteger value);
    public IStructAbiEncoder Int88(BigInteger value);
    public IStructAbiEncoder UInt88(BigInteger value);
    public IStructAbiEncoder Int96(BigInteger value);
    public IStructAbiEncoder UInt96(BigInteger value);
    public IStructAbiEncoder Int104(BigInteger value);
    public IStructAbiEncoder UInt104(BigInteger value);
    public IStructAbiEncoder Int112(BigInteger value);
    public IStructAbiEncoder UInt112(BigInteger value);
    public IStructAbiEncoder Int120(BigInteger value);
    public IStructAbiEncoder UInt120(BigInteger value);
    public IStructAbiEncoder Int128(BigInteger value);
    public IStructAbiEncoder UInt128(BigInteger value);
    public IStructAbiEncoder Int136(BigInteger value);
    public IStructAbiEncoder UInt136(BigInteger value);
    public IStructAbiEncoder Int144(BigInteger value);
    public IStructAbiEncoder UInt144(BigInteger value);
    public IStructAbiEncoder Int152(BigInteger value);
    public IStructAbiEncoder UInt152(BigInteger value);
    public IStructAbiEncoder Int160(BigInteger value);
    public IStructAbiEncoder UInt160(BigInteger value);
    public IStructAbiEncoder Int168(BigInteger value);
    public IStructAbiEncoder UInt168(BigInteger value);
    public IStructAbiEncoder Int176(BigInteger value);
    public IStructAbiEncoder UInt176(BigInteger value);
    public IStructAbiEncoder Int184(BigInteger value);
    public IStructAbiEncoder UInt184(BigInteger value);
    public IStructAbiEncoder Int192(BigInteger value);
    public IStructAbiEncoder UInt192(BigInteger value);
    public IStructAbiEncoder Int200(BigInteger value);
    public IStructAbiEncoder UInt200(BigInteger value);
    public IStructAbiEncoder Int208(BigInteger value);
    public IStructAbiEncoder UInt208(BigInteger value);
    public IStructAbiEncoder Int216(BigInteger value);
    public IStructAbiEncoder UInt216(BigInteger value);
    public IStructAbiEncoder Int224(BigInteger value);
    public IStructAbiEncoder UInt224(BigInteger value);
    public IStructAbiEncoder Int232(BigInteger value);
    public IStructAbiEncoder UInt232(BigInteger value);
    public IStructAbiEncoder Int240(BigInteger value);
    public IStructAbiEncoder UInt240(BigInteger value);
    public IStructAbiEncoder Int248(BigInteger value);
    public IStructAbiEncoder UInt248(BigInteger value);
    public IStructAbiEncoder Int256(BigInteger value);
    public IStructAbiEncoder UInt256(BigInteger value);
}