// <auto-generated/>
#nullable enable
using EtherSharp.Types;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EtherSharp.Common.Converter;

internal static class FixedBytesJsonConverters
{
    public static void Register(IList<JsonConverter> converters)
    {
        converters.Add(new Bytes1Converter());
        converters.Add(new Bytes2Converter());
        converters.Add(new Bytes3Converter());
        converters.Add(new Bytes4Converter());
        converters.Add(new Bytes5Converter());
        converters.Add(new Bytes6Converter());
        converters.Add(new Bytes7Converter());
        converters.Add(new Bytes8Converter());
        converters.Add(new Bytes9Converter());
        converters.Add(new Bytes10Converter());
        converters.Add(new Bytes11Converter());
        converters.Add(new Bytes12Converter());
        converters.Add(new Bytes13Converter());
        converters.Add(new Bytes14Converter());
        converters.Add(new Bytes15Converter());
        converters.Add(new Bytes16Converter());
        converters.Add(new Bytes17Converter());
        converters.Add(new Bytes18Converter());
        converters.Add(new Bytes19Converter());
        converters.Add(new Bytes20Converter());
        converters.Add(new Bytes21Converter());
        converters.Add(new Bytes22Converter());
        converters.Add(new Bytes23Converter());
        converters.Add(new Bytes24Converter());
        converters.Add(new Bytes25Converter());
        converters.Add(new Bytes26Converter());
        converters.Add(new Bytes27Converter());
        converters.Add(new Bytes28Converter());
        converters.Add(new Bytes29Converter());
        converters.Add(new Bytes30Converter());
        converters.Add(new Bytes31Converter());
        converters.Add(new Bytes32Converter());
    }
}

/// <summary>
/// Converts <see cref="Bytes1"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes1Converter : FixedBytesJsonConverter<Bytes1>
{
}

/// <summary>
/// Converts <see cref="Bytes2"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes2Converter : FixedBytesJsonConverter<Bytes2>
{
}

/// <summary>
/// Converts <see cref="Bytes3"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes3Converter : FixedBytesJsonConverter<Bytes3>
{
}

/// <summary>
/// Converts <see cref="Bytes4"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes4Converter : FixedBytesJsonConverter<Bytes4>
{
}

/// <summary>
/// Converts <see cref="Bytes5"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes5Converter : FixedBytesJsonConverter<Bytes5>
{
}

/// <summary>
/// Converts <see cref="Bytes6"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes6Converter : FixedBytesJsonConverter<Bytes6>
{
}

/// <summary>
/// Converts <see cref="Bytes7"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes7Converter : FixedBytesJsonConverter<Bytes7>
{
}

/// <summary>
/// Converts <see cref="Bytes8"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes8Converter : FixedBytesJsonConverter<Bytes8>
{
}

/// <summary>
/// Converts <see cref="Bytes9"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes9Converter : FixedBytesJsonConverter<Bytes9>
{
}

/// <summary>
/// Converts <see cref="Bytes10"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes10Converter : FixedBytesJsonConverter<Bytes10>
{
}

/// <summary>
/// Converts <see cref="Bytes11"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes11Converter : FixedBytesJsonConverter<Bytes11>
{
}

/// <summary>
/// Converts <see cref="Bytes12"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes12Converter : FixedBytesJsonConverter<Bytes12>
{
}

/// <summary>
/// Converts <see cref="Bytes13"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes13Converter : FixedBytesJsonConverter<Bytes13>
{
}

/// <summary>
/// Converts <see cref="Bytes14"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes14Converter : FixedBytesJsonConverter<Bytes14>
{
}

/// <summary>
/// Converts <see cref="Bytes15"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes15Converter : FixedBytesJsonConverter<Bytes15>
{
}

/// <summary>
/// Converts <see cref="Bytes16"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes16Converter : FixedBytesJsonConverter<Bytes16>
{
}

/// <summary>
/// Converts <see cref="Bytes17"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes17Converter : FixedBytesJsonConverter<Bytes17>
{
}

/// <summary>
/// Converts <see cref="Bytes18"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes18Converter : FixedBytesJsonConverter<Bytes18>
{
}

/// <summary>
/// Converts <see cref="Bytes19"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes19Converter : FixedBytesJsonConverter<Bytes19>
{
}

/// <summary>
/// Converts <see cref="Bytes20"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes20Converter : FixedBytesJsonConverter<Bytes20>
{
}

/// <summary>
/// Converts <see cref="Bytes21"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes21Converter : FixedBytesJsonConverter<Bytes21>
{
}

/// <summary>
/// Converts <see cref="Bytes22"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes22Converter : FixedBytesJsonConverter<Bytes22>
{
}

/// <summary>
/// Converts <see cref="Bytes23"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes23Converter : FixedBytesJsonConverter<Bytes23>
{
}

/// <summary>
/// Converts <see cref="Bytes24"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes24Converter : FixedBytesJsonConverter<Bytes24>
{
}

/// <summary>
/// Converts <see cref="Bytes25"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes25Converter : FixedBytesJsonConverter<Bytes25>
{
}

/// <summary>
/// Converts <see cref="Bytes26"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes26Converter : FixedBytesJsonConverter<Bytes26>
{
}

/// <summary>
/// Converts <see cref="Bytes27"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes27Converter : FixedBytesJsonConverter<Bytes27>
{
}

/// <summary>
/// Converts <see cref="Bytes28"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes28Converter : FixedBytesJsonConverter<Bytes28>
{
}

/// <summary>
/// Converts <see cref="Bytes29"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes29Converter : FixedBytesJsonConverter<Bytes29>
{
}

/// <summary>
/// Converts <see cref="Bytes30"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes30Converter : FixedBytesJsonConverter<Bytes30>
{
}

/// <summary>
/// Converts <see cref="Bytes31"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes31Converter : FixedBytesJsonConverter<Bytes31>
{
}

/// <summary>
/// Converts <see cref="Bytes32"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes32Converter : FixedBytesJsonConverter<Bytes32>
{
}
