// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
using EtherSharp.Types;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace EtherSharp.Common.Converter;

internal static class FixedBytesJsonConverters
{
    public static void Register(IList<JsonConverter> converters)
    {
        converters.Add(Bytes1Converter.Instance);
        converters.Add(Bytes2Converter.Instance);
        converters.Add(Bytes3Converter.Instance);
        converters.Add(Bytes4Converter.Instance);
        converters.Add(Bytes5Converter.Instance);
        converters.Add(Bytes6Converter.Instance);
        converters.Add(Bytes7Converter.Instance);
        converters.Add(Bytes8Converter.Instance);
        converters.Add(Bytes9Converter.Instance);
        converters.Add(Bytes10Converter.Instance);
        converters.Add(Bytes11Converter.Instance);
        converters.Add(Bytes12Converter.Instance);
        converters.Add(Bytes13Converter.Instance);
        converters.Add(Bytes14Converter.Instance);
        converters.Add(Bytes15Converter.Instance);
        converters.Add(Bytes16Converter.Instance);
        converters.Add(Bytes17Converter.Instance);
        converters.Add(Bytes18Converter.Instance);
        converters.Add(Bytes19Converter.Instance);
        converters.Add(Bytes20Converter.Instance);
        converters.Add(Bytes21Converter.Instance);
        converters.Add(Bytes22Converter.Instance);
        converters.Add(Bytes23Converter.Instance);
        converters.Add(Bytes24Converter.Instance);
        converters.Add(Bytes25Converter.Instance);
        converters.Add(Bytes26Converter.Instance);
        converters.Add(Bytes27Converter.Instance);
        converters.Add(Bytes28Converter.Instance);
        converters.Add(Bytes29Converter.Instance);
        converters.Add(Bytes30Converter.Instance);
        converters.Add(Bytes31Converter.Instance);
        converters.Add(Bytes32Converter.Instance);
    }
}

/// <summary>
/// Converts <see cref="Bytes1"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes1Converter : FixedBytesJsonConverter<Bytes1>
{
    public static Bytes1Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes1 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes2"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes2Converter : FixedBytesJsonConverter<Bytes2>
{
    public static Bytes2Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes2 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes3"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes3Converter : FixedBytesJsonConverter<Bytes3>
{
    public static Bytes3Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes3 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes4"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes4Converter : FixedBytesJsonConverter<Bytes4>
{
    public static Bytes4Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes4 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes5"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes5Converter : FixedBytesJsonConverter<Bytes5>
{
    public static Bytes5Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes5 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes6"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes6Converter : FixedBytesJsonConverter<Bytes6>
{
    public static Bytes6Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes6 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes7"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes7Converter : FixedBytesJsonConverter<Bytes7>
{
    public static Bytes7Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes7 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes8"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes8Converter : FixedBytesJsonConverter<Bytes8>
{
    public static Bytes8Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes8 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes9"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes9Converter : FixedBytesJsonConverter<Bytes9>
{
    public static Bytes9Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes9 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes10"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes10Converter : FixedBytesJsonConverter<Bytes10>
{
    public static Bytes10Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes10 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes11"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes11Converter : FixedBytesJsonConverter<Bytes11>
{
    public static Bytes11Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes11 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes12"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes12Converter : FixedBytesJsonConverter<Bytes12>
{
    public static Bytes12Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes12 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes13"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes13Converter : FixedBytesJsonConverter<Bytes13>
{
    public static Bytes13Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes13 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes14"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes14Converter : FixedBytesJsonConverter<Bytes14>
{
    public static Bytes14Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes14 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes15"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes15Converter : FixedBytesJsonConverter<Bytes15>
{
    public static Bytes15Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes15 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes16"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes16Converter : FixedBytesJsonConverter<Bytes16>
{
    public static Bytes16Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes16 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes17"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes17Converter : FixedBytesJsonConverter<Bytes17>
{
    public static Bytes17Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes17 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes18"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes18Converter : FixedBytesJsonConverter<Bytes18>
{
    public static Bytes18Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes18 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes19"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes19Converter : FixedBytesJsonConverter<Bytes19>
{
    public static Bytes19Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes19 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes20"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes20Converter : FixedBytesJsonConverter<Bytes20>
{
    public static Bytes20Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes20 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes21"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes21Converter : FixedBytesJsonConverter<Bytes21>
{
    public static Bytes21Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes21 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes22"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes22Converter : FixedBytesJsonConverter<Bytes22>
{
    public static Bytes22Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes22 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes23"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes23Converter : FixedBytesJsonConverter<Bytes23>
{
    public static Bytes23Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes23 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes24"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes24Converter : FixedBytesJsonConverter<Bytes24>
{
    public static Bytes24Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes24 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes25"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes25Converter : FixedBytesJsonConverter<Bytes25>
{
    public static Bytes25Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes25 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes26"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes26Converter : FixedBytesJsonConverter<Bytes26>
{
    public static Bytes26Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes26 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes27"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes27Converter : FixedBytesJsonConverter<Bytes27>
{
    public static Bytes27Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes27 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes28"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes28Converter : FixedBytesJsonConverter<Bytes28>
{
    public static Bytes28Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes28 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes29"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes29Converter : FixedBytesJsonConverter<Bytes29>
{
    public static Bytes29Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes29 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes30"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes30Converter : FixedBytesJsonConverter<Bytes30>
{
    public static Bytes30Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes30 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes31"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes31Converter : FixedBytesJsonConverter<Bytes31>
{
    public static Bytes31Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes31 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}

/// <summary>
/// Converts <see cref="Bytes32"/> values to and from 0x-prefixed hex strings.
/// </summary>
public sealed class Bytes32Converter : FixedBytesJsonConverter<Bytes32>
{
    public static Bytes32Converter Instance { get; } = new();

    /// <inheritdoc/>
    protected override void WriteUnsafe(Utf8JsonWriter writer, Bytes32 value)
        => HexJsonConverter.WriteBytes(writer, value.DangerousGetReadOnlySpan());
}


