using EtherSharp.Generator.SyntaxElements;
using EtherSharp.Generator.Util;

namespace EtherSharp.Generator.EIP712;

public static class EIP712SourceWriter
{
    public static string Write(EIP712GenerationModel model)
    {
        string namespaceDeclaration = model.Type.Symbol.ContainingNamespace.IsGlobalNamespace
            ? String.Empty
            : $"namespace {model.Type.Symbol.ContainingNamespace};\n\n";
        string typeName = NameUtils.EscapeIdentifier(model.Type.Symbol.Name);
        string typeHashField = Indent(BuildTypeHashField(model.TypeHash));
        string hashStructFunction = Indent(BuildHashStructFunction(model.Type.Members));

        return $$"""
            // <auto-generated/>
            #nullable enable
            {{namespaceDeclaration}}{{model.DeclarationKind}} {{typeName}}
            {
            {{typeHashField}}

            {{hashStructFunction}}
            }
            """;
    }

    private static string BuildTypeHashField(byte[] typeHash)
    {
        string bytes = String.Join(", ", typeHash.Select(static value => $"0x{value:x2}"));
        string initializer = $$"""
            global::EtherSharp.Types.Bytes32.FromBytes(new byte[]
            {
                {{bytes}}
            })
            """;

        return new FieldBuilder(
                "global::EtherSharp.Types.Bytes32",
                "__etherSharpEIP712TypeHash")
            .WithVisibility(FieldVisibility.Private)
            .WithIsStatic()
            .WithIsReadonly()
            .WithDefaultValue(initializer)
            .Build();
    }

    private static string BuildHashStructFunction(IReadOnlyList<EIP712MemberModel> members)
    {
        string memberEncoders = String.Join(
            "\n",
            members.Select(static member => $"    .{GetEncodingCall(member)}"));
        string encoderStatement = $$"""
            var encoder = new global::EtherSharp.ABI.AbiEncoder()
                .Bytes32(__etherSharpEIP712TypeHash)
            {{memberEncoders}}
            """.TrimEnd();

        return "/// <inheritdoc/>\n" + new FunctionBuilder("HashStruct")
            .WithReturnTypeRaw("global::EtherSharp.Types.Bytes32")
            .AddStatement(Indent(encoderStatement))
            .AddStatement("    return global::EtherSharp.Crypto.Keccak256.HashData(encoder.Build())")
            .BuildMethodCode();
    }

    private static string GetEncodingCall(EIP712MemberModel member)
    {
        string value = $"this.{member.PropertyName}";
        return member.EncodingKind switch
        {
            EIP712EncodingKind.Bool => $"Bool({value})",
            EIP712EncodingKind.Address => $"Address({value})",
            EIP712EncodingKind.UInt256 => $"UInt256({value})",
            EIP712EncodingKind.Int256 => $"Int256({value})",
            EIP712EncodingKind.FixedBytes => $"Bytes{member.FixedBytesLength}({value})",
            EIP712EncodingKind.String => $"Bytes32(global::EtherSharp.Crypto.Keccak256.HashData({value}))",
            EIP712EncodingKind.ByteArray => $"Bytes32(global::EtherSharp.Crypto.Keccak256.HashData({value}))",
            EIP712EncodingKind.ReadOnlyMemory => $"Bytes32(global::EtherSharp.Crypto.Keccak256.HashData({value}.Span))",
            EIP712EncodingKind.Struct => $"Bytes32({value}.HashStruct())",
            _ => throw new NotSupportedException(member.EncodingKind.ToString())
        };
    }

    private static string Indent(string value)
        => "    " + value.TrimEnd('\r', '\n').Replace("\n", "\n    ");
}
