// <auto-generated/>
using EtherSharp.ABI.Decode.Interfaces;
using EtherSharp.ABI.Types;
using EtherSharp.Types;

namespace EtherSharp.ABI;

public partial class AbiDecoder
{
    /// <summary>
    /// Reads a bytes1 value from the input.
    /// </summary>
    /// <returns>The decoded 1-byte value.</returns>
    public Bytes1 Bytes1()
    {
        var result = AbiTypes.SizedBytes<Bytes1>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes1 IFixedTupleDecoder.Bytes1()
        => Bytes1();
    Bytes1 IDynamicTupleDecoder.Bytes1()
        => Bytes1();

    /// <summary>
    /// Reads a bytes2 value from the input.
    /// </summary>
    /// <returns>The decoded 2-byte value.</returns>
    public Bytes2 Bytes2()
    {
        var result = AbiTypes.SizedBytes<Bytes2>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes2 IFixedTupleDecoder.Bytes2()
        => Bytes2();
    Bytes2 IDynamicTupleDecoder.Bytes2()
        => Bytes2();

    /// <summary>
    /// Reads a bytes3 value from the input.
    /// </summary>
    /// <returns>The decoded 3-byte value.</returns>
    public Bytes3 Bytes3()
    {
        var result = AbiTypes.SizedBytes<Bytes3>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes3 IFixedTupleDecoder.Bytes3()
        => Bytes3();
    Bytes3 IDynamicTupleDecoder.Bytes3()
        => Bytes3();

    /// <summary>
    /// Reads a bytes4 value from the input.
    /// </summary>
    /// <returns>The decoded 4-byte value.</returns>
    public Bytes4 Bytes4()
    {
        var result = AbiTypes.SizedBytes<Bytes4>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes4 IFixedTupleDecoder.Bytes4()
        => Bytes4();
    Bytes4 IDynamicTupleDecoder.Bytes4()
        => Bytes4();

    /// <summary>
    /// Reads a bytes5 value from the input.
    /// </summary>
    /// <returns>The decoded 5-byte value.</returns>
    public Bytes5 Bytes5()
    {
        var result = AbiTypes.SizedBytes<Bytes5>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes5 IFixedTupleDecoder.Bytes5()
        => Bytes5();
    Bytes5 IDynamicTupleDecoder.Bytes5()
        => Bytes5();

    /// <summary>
    /// Reads a bytes6 value from the input.
    /// </summary>
    /// <returns>The decoded 6-byte value.</returns>
    public Bytes6 Bytes6()
    {
        var result = AbiTypes.SizedBytes<Bytes6>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes6 IFixedTupleDecoder.Bytes6()
        => Bytes6();
    Bytes6 IDynamicTupleDecoder.Bytes6()
        => Bytes6();

    /// <summary>
    /// Reads a bytes7 value from the input.
    /// </summary>
    /// <returns>The decoded 7-byte value.</returns>
    public Bytes7 Bytes7()
    {
        var result = AbiTypes.SizedBytes<Bytes7>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes7 IFixedTupleDecoder.Bytes7()
        => Bytes7();
    Bytes7 IDynamicTupleDecoder.Bytes7()
        => Bytes7();

    /// <summary>
    /// Reads a bytes8 value from the input.
    /// </summary>
    /// <returns>The decoded 8-byte value.</returns>
    public Bytes8 Bytes8()
    {
        var result = AbiTypes.SizedBytes<Bytes8>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes8 IFixedTupleDecoder.Bytes8()
        => Bytes8();
    Bytes8 IDynamicTupleDecoder.Bytes8()
        => Bytes8();

    /// <summary>
    /// Reads a bytes9 value from the input.
    /// </summary>
    /// <returns>The decoded 9-byte value.</returns>
    public Bytes9 Bytes9()
    {
        var result = AbiTypes.SizedBytes<Bytes9>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes9 IFixedTupleDecoder.Bytes9()
        => Bytes9();
    Bytes9 IDynamicTupleDecoder.Bytes9()
        => Bytes9();

    /// <summary>
    /// Reads a bytes10 value from the input.
    /// </summary>
    /// <returns>The decoded 10-byte value.</returns>
    public Bytes10 Bytes10()
    {
        var result = AbiTypes.SizedBytes<Bytes10>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes10 IFixedTupleDecoder.Bytes10()
        => Bytes10();
    Bytes10 IDynamicTupleDecoder.Bytes10()
        => Bytes10();

    /// <summary>
    /// Reads a bytes11 value from the input.
    /// </summary>
    /// <returns>The decoded 11-byte value.</returns>
    public Bytes11 Bytes11()
    {
        var result = AbiTypes.SizedBytes<Bytes11>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes11 IFixedTupleDecoder.Bytes11()
        => Bytes11();
    Bytes11 IDynamicTupleDecoder.Bytes11()
        => Bytes11();

    /// <summary>
    /// Reads a bytes12 value from the input.
    /// </summary>
    /// <returns>The decoded 12-byte value.</returns>
    public Bytes12 Bytes12()
    {
        var result = AbiTypes.SizedBytes<Bytes12>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes12 IFixedTupleDecoder.Bytes12()
        => Bytes12();
    Bytes12 IDynamicTupleDecoder.Bytes12()
        => Bytes12();

    /// <summary>
    /// Reads a bytes13 value from the input.
    /// </summary>
    /// <returns>The decoded 13-byte value.</returns>
    public Bytes13 Bytes13()
    {
        var result = AbiTypes.SizedBytes<Bytes13>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes13 IFixedTupleDecoder.Bytes13()
        => Bytes13();
    Bytes13 IDynamicTupleDecoder.Bytes13()
        => Bytes13();

    /// <summary>
    /// Reads a bytes14 value from the input.
    /// </summary>
    /// <returns>The decoded 14-byte value.</returns>
    public Bytes14 Bytes14()
    {
        var result = AbiTypes.SizedBytes<Bytes14>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes14 IFixedTupleDecoder.Bytes14()
        => Bytes14();
    Bytes14 IDynamicTupleDecoder.Bytes14()
        => Bytes14();

    /// <summary>
    /// Reads a bytes15 value from the input.
    /// </summary>
    /// <returns>The decoded 15-byte value.</returns>
    public Bytes15 Bytes15()
    {
        var result = AbiTypes.SizedBytes<Bytes15>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes15 IFixedTupleDecoder.Bytes15()
        => Bytes15();
    Bytes15 IDynamicTupleDecoder.Bytes15()
        => Bytes15();

    /// <summary>
    /// Reads a bytes16 value from the input.
    /// </summary>
    /// <returns>The decoded 16-byte value.</returns>
    public Bytes16 Bytes16()
    {
        var result = AbiTypes.SizedBytes<Bytes16>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes16 IFixedTupleDecoder.Bytes16()
        => Bytes16();
    Bytes16 IDynamicTupleDecoder.Bytes16()
        => Bytes16();

    /// <summary>
    /// Reads a bytes17 value from the input.
    /// </summary>
    /// <returns>The decoded 17-byte value.</returns>
    public Bytes17 Bytes17()
    {
        var result = AbiTypes.SizedBytes<Bytes17>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes17 IFixedTupleDecoder.Bytes17()
        => Bytes17();
    Bytes17 IDynamicTupleDecoder.Bytes17()
        => Bytes17();

    /// <summary>
    /// Reads a bytes18 value from the input.
    /// </summary>
    /// <returns>The decoded 18-byte value.</returns>
    public Bytes18 Bytes18()
    {
        var result = AbiTypes.SizedBytes<Bytes18>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes18 IFixedTupleDecoder.Bytes18()
        => Bytes18();
    Bytes18 IDynamicTupleDecoder.Bytes18()
        => Bytes18();

    /// <summary>
    /// Reads a bytes19 value from the input.
    /// </summary>
    /// <returns>The decoded 19-byte value.</returns>
    public Bytes19 Bytes19()
    {
        var result = AbiTypes.SizedBytes<Bytes19>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes19 IFixedTupleDecoder.Bytes19()
        => Bytes19();
    Bytes19 IDynamicTupleDecoder.Bytes19()
        => Bytes19();

    /// <summary>
    /// Reads a bytes20 value from the input.
    /// </summary>
    /// <returns>The decoded 20-byte value.</returns>
    public Bytes20 Bytes20()
    {
        var result = AbiTypes.SizedBytes<Bytes20>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes20 IFixedTupleDecoder.Bytes20()
        => Bytes20();
    Bytes20 IDynamicTupleDecoder.Bytes20()
        => Bytes20();

    /// <summary>
    /// Reads a bytes21 value from the input.
    /// </summary>
    /// <returns>The decoded 21-byte value.</returns>
    public Bytes21 Bytes21()
    {
        var result = AbiTypes.SizedBytes<Bytes21>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes21 IFixedTupleDecoder.Bytes21()
        => Bytes21();
    Bytes21 IDynamicTupleDecoder.Bytes21()
        => Bytes21();

    /// <summary>
    /// Reads a bytes22 value from the input.
    /// </summary>
    /// <returns>The decoded 22-byte value.</returns>
    public Bytes22 Bytes22()
    {
        var result = AbiTypes.SizedBytes<Bytes22>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes22 IFixedTupleDecoder.Bytes22()
        => Bytes22();
    Bytes22 IDynamicTupleDecoder.Bytes22()
        => Bytes22();

    /// <summary>
    /// Reads a bytes23 value from the input.
    /// </summary>
    /// <returns>The decoded 23-byte value.</returns>
    public Bytes23 Bytes23()
    {
        var result = AbiTypes.SizedBytes<Bytes23>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes23 IFixedTupleDecoder.Bytes23()
        => Bytes23();
    Bytes23 IDynamicTupleDecoder.Bytes23()
        => Bytes23();

    /// <summary>
    /// Reads a bytes24 value from the input.
    /// </summary>
    /// <returns>The decoded 24-byte value.</returns>
    public Bytes24 Bytes24()
    {
        var result = AbiTypes.SizedBytes<Bytes24>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes24 IFixedTupleDecoder.Bytes24()
        => Bytes24();
    Bytes24 IDynamicTupleDecoder.Bytes24()
        => Bytes24();

    /// <summary>
    /// Reads a bytes25 value from the input.
    /// </summary>
    /// <returns>The decoded 25-byte value.</returns>
    public Bytes25 Bytes25()
    {
        var result = AbiTypes.SizedBytes<Bytes25>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes25 IFixedTupleDecoder.Bytes25()
        => Bytes25();
    Bytes25 IDynamicTupleDecoder.Bytes25()
        => Bytes25();

    /// <summary>
    /// Reads a bytes26 value from the input.
    /// </summary>
    /// <returns>The decoded 26-byte value.</returns>
    public Bytes26 Bytes26()
    {
        var result = AbiTypes.SizedBytes<Bytes26>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes26 IFixedTupleDecoder.Bytes26()
        => Bytes26();
    Bytes26 IDynamicTupleDecoder.Bytes26()
        => Bytes26();

    /// <summary>
    /// Reads a bytes27 value from the input.
    /// </summary>
    /// <returns>The decoded 27-byte value.</returns>
    public Bytes27 Bytes27()
    {
        var result = AbiTypes.SizedBytes<Bytes27>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes27 IFixedTupleDecoder.Bytes27()
        => Bytes27();
    Bytes27 IDynamicTupleDecoder.Bytes27()
        => Bytes27();

    /// <summary>
    /// Reads a bytes28 value from the input.
    /// </summary>
    /// <returns>The decoded 28-byte value.</returns>
    public Bytes28 Bytes28()
    {
        var result = AbiTypes.SizedBytes<Bytes28>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes28 IFixedTupleDecoder.Bytes28()
        => Bytes28();
    Bytes28 IDynamicTupleDecoder.Bytes28()
        => Bytes28();

    /// <summary>
    /// Reads a bytes29 value from the input.
    /// </summary>
    /// <returns>The decoded 29-byte value.</returns>
    public Bytes29 Bytes29()
    {
        var result = AbiTypes.SizedBytes<Bytes29>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes29 IFixedTupleDecoder.Bytes29()
        => Bytes29();
    Bytes29 IDynamicTupleDecoder.Bytes29()
        => Bytes29();

    /// <summary>
    /// Reads a bytes30 value from the input.
    /// </summary>
    /// <returns>The decoded 30-byte value.</returns>
    public Bytes30 Bytes30()
    {
        var result = AbiTypes.SizedBytes<Bytes30>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes30 IFixedTupleDecoder.Bytes30()
        => Bytes30();
    Bytes30 IDynamicTupleDecoder.Bytes30()
        => Bytes30();

    /// <summary>
    /// Reads a bytes31 value from the input.
    /// </summary>
    /// <returns>The decoded 31-byte value.</returns>
    public Bytes31 Bytes31()
    {
        var result = AbiTypes.SizedBytes<Bytes31>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes31 IFixedTupleDecoder.Bytes31()
        => Bytes31();
    Bytes31 IDynamicTupleDecoder.Bytes31()
        => Bytes31();

    /// <summary>
    /// Reads a bytes32 value from the input.
    /// </summary>
    /// <returns>The decoded 32-byte value.</returns>
    public Bytes32 Bytes32()
    {
        var result = AbiTypes.SizedBytes<Bytes32>.Decode(_bytes.Slice(BytesRead, 32));
        ConsumeBytes();
        return result;
    }
    Bytes32 IFixedTupleDecoder.Bytes32()
        => Bytes32();
    Bytes32 IDynamicTupleDecoder.Bytes32()
        => Bytes32();

}
