// <auto-generated/>
using EtherSharp.ABI.Types;
using EtherSharp.Types;

namespace EtherSharp.ABI;

public partial class AbiDecoder
{
    /// <summary>
    /// Reads a bytes1 array from the input.
    /// </summary>
    /// <returns>The decoded byte array.</returns>
    public Bytes1[] Bytes1Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes1>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes2 array from the input.
    /// </summary>
    /// <returns>The decoded array of 2-byte values.</returns>
    public Bytes2[] Bytes2Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes2>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes3 array from the input.
    /// </summary>
    /// <returns>The decoded array of 3-byte values.</returns>
    public Bytes3[] Bytes3Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes3>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes4 array from the input.
    /// </summary>
    /// <returns>The decoded array of 4-byte values.</returns>
    public Bytes4[] Bytes4Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes4>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes5 array from the input.
    /// </summary>
    /// <returns>The decoded array of 5-byte values.</returns>
    public Bytes5[] Bytes5Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes5>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes6 array from the input.
    /// </summary>
    /// <returns>The decoded array of 6-byte values.</returns>
    public Bytes6[] Bytes6Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes6>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes7 array from the input.
    /// </summary>
    /// <returns>The decoded array of 7-byte values.</returns>
    public Bytes7[] Bytes7Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes7>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes8 array from the input.
    /// </summary>
    /// <returns>The decoded array of 8-byte values.</returns>
    public Bytes8[] Bytes8Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes8>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes9 array from the input.
    /// </summary>
    /// <returns>The decoded array of 9-byte values.</returns>
    public Bytes9[] Bytes9Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes9>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes10 array from the input.
    /// </summary>
    /// <returns>The decoded array of 10-byte values.</returns>
    public Bytes10[] Bytes10Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes10>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes11 array from the input.
    /// </summary>
    /// <returns>The decoded array of 11-byte values.</returns>
    public Bytes11[] Bytes11Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes11>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes12 array from the input.
    /// </summary>
    /// <returns>The decoded array of 12-byte values.</returns>
    public Bytes12[] Bytes12Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes12>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes13 array from the input.
    /// </summary>
    /// <returns>The decoded array of 13-byte values.</returns>
    public Bytes13[] Bytes13Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes13>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes14 array from the input.
    /// </summary>
    /// <returns>The decoded array of 14-byte values.</returns>
    public Bytes14[] Bytes14Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes14>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes15 array from the input.
    /// </summary>
    /// <returns>The decoded array of 15-byte values.</returns>
    public Bytes15[] Bytes15Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes15>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes16 array from the input.
    /// </summary>
    /// <returns>The decoded array of 16-byte values.</returns>
    public Bytes16[] Bytes16Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes16>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes17 array from the input.
    /// </summary>
    /// <returns>The decoded array of 17-byte values.</returns>
    public Bytes17[] Bytes17Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes17>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes18 array from the input.
    /// </summary>
    /// <returns>The decoded array of 18-byte values.</returns>
    public Bytes18[] Bytes18Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes18>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes19 array from the input.
    /// </summary>
    /// <returns>The decoded array of 19-byte values.</returns>
    public Bytes19[] Bytes19Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes19>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes20 array from the input.
    /// </summary>
    /// <returns>The decoded array of 20-byte values.</returns>
    public Bytes20[] Bytes20Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes20>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes21 array from the input.
    /// </summary>
    /// <returns>The decoded array of 21-byte values.</returns>
    public Bytes21[] Bytes21Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes21>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes22 array from the input.
    /// </summary>
    /// <returns>The decoded array of 22-byte values.</returns>
    public Bytes22[] Bytes22Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes22>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes23 array from the input.
    /// </summary>
    /// <returns>The decoded array of 23-byte values.</returns>
    public Bytes23[] Bytes23Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes23>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes24 array from the input.
    /// </summary>
    /// <returns>The decoded array of 24-byte values.</returns>
    public Bytes24[] Bytes24Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes24>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes25 array from the input.
    /// </summary>
    /// <returns>The decoded array of 25-byte values.</returns>
    public Bytes25[] Bytes25Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes25>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes26 array from the input.
    /// </summary>
    /// <returns>The decoded array of 26-byte values.</returns>
    public Bytes26[] Bytes26Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes26>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes27 array from the input.
    /// </summary>
    /// <returns>The decoded array of 27-byte values.</returns>
    public Bytes27[] Bytes27Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes27>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes28 array from the input.
    /// </summary>
    /// <returns>The decoded array of 28-byte values.</returns>
    public Bytes28[] Bytes28Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes28>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes29 array from the input.
    /// </summary>
    /// <returns>The decoded array of 29-byte values.</returns>
    public Bytes29[] Bytes29Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes29>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes30 array from the input.
    /// </summary>
    /// <returns>The decoded array of 30-byte values.</returns>
    public Bytes30[] Bytes30Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes30>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes31 array from the input.
    /// </summary>
    /// <returns>The decoded array of 31-byte values.</returns>
    public Bytes31[] Bytes31Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes31>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
    /// <summary>
    /// Reads a bytes32 array from the input.
    /// </summary>
    /// <returns>The decoded array of 32-byte values.</returns>
    public Bytes32[] Bytes32Array()
    {
        var result = AbiTypes.SizedBytesArray<Bytes32>.Decode(_bytes, BytesRead);
        ConsumeBytes();
        return result;
    }
}
