// <auto-generated/>
#nullable enable
using EtherSharp.Types;

namespace EtherSharp.Common.Extensions;

/// <summary>
/// Provides fixed-size byte search helpers for read-only byte spans.
/// </summary>
public static class ReadOnlySpanExtensions
{
    extension(ReadOnlySpan<byte> span)
    {
        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes1 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes1 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes2 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes2 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes3 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes3 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes4 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes4 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes5 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes5 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes6 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes6 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes7 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes7 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes8 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes8 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes9 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes9 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes10 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes10 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes11 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes11 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes12 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes12 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes13 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes13 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes14 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes14 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes15 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes15 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes16 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes16 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes17 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes17 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes18 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes18 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes19 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes19 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes20 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes20 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes21 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes21 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes22 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes22 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes23 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes23 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes24 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes24 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes25 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes25 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes26 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes26 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes27 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes27 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes28 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes28 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes29 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes29 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes30 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes30 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes31 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes31 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Bytes32 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The fixed-size byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Bytes32 value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());

        /// <summary>
        /// Determines whether <paramref name="span"/> contains <paramref name="value"/>.
        /// </summary>
        /// <param name="value">The address byte sequence to find.</param>
        /// <returns>True when <paramref name="value"/> occurs in <paramref name="span"/>; otherwise false.</returns>
        public bool Contains(in Address value)
            => span.IndexOf(value.DangerousGetReadOnlySpan()) >= 0;

        /// <summary>
        /// Finds the first occurrence of <paramref name="value"/> in <paramref name="span"/>.
        /// </summary>
        /// <param name="value">The address byte sequence to find.</param>
        /// <returns>The zero-based index of <paramref name="value"/>, or -1 when it is not found.</returns>
        public int IndexOf(in Address value)
            => span.IndexOf(value.DangerousGetReadOnlySpan());
    }
}
