// <auto-generated/>
namespace EtherSharp.Query;

internal sealed record CombinedQuery<T1, T2>(IQuery<T1> Q1, IQuery<T2> Q2) : IQuery<(T1, T2)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount;

    void IQuery<(T1, T2)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
    }

    (T1, T2) IQuery<(T1, T2)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3) : IQuery<(T1, T2, T3)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount;

    void IQuery<(T1, T2, T3)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
    }

    (T1, T2, T3) IQuery<(T1, T2, T3)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4) : IQuery<(T1, T2, T3, T4)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount;

    void IQuery<(T1, T2, T3, T4)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
    }

    (T1, T2, T3, T4) IQuery<(T1, T2, T3, T4)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5) : IQuery<(T1, T2, T3, T4, T5)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
    }

    (T1, T2, T3, T4, T5) IQuery<(T1, T2, T3, T4, T5)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6) : IQuery<(T1, T2, T3, T4, T5, T6)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
    }

    (T1, T2, T3, T4, T5, T6) IQuery<(T1, T2, T3, T4, T5, T6)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7) : IQuery<(T1, T2, T3, T4, T5, T6, T7)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
    }

    (T1, T2, T3, T4, T5, T6, T7) IQuery<(T1, T2, T3, T4, T5, T6, T7)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7, IQuery<T8> Q8) : IQuery<(T1, T2, T3, T4, T5, T6, T7, T8)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount + Q8.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7, T8)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
        plan.Add(Q8);
    }

    (T1, T2, T3, T4, T5, T6, T7, T8) IQuery<(T1, T2, T3, T4, T5, T6, T7, T8)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)]),
            Q8.ReadResultFrom(results[offset..(offset += Q8.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7, IQuery<T8> Q8, IQuery<T9> Q9) : IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount + Q8.OperationCount + Q9.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
        plan.Add(Q8);
        plan.Add(Q9);
    }

    (T1, T2, T3, T4, T5, T6, T7, T8, T9) IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)]),
            Q8.ReadResultFrom(results[offset..(offset += Q8.OperationCount)]),
            Q9.ReadResultFrom(results[offset..(offset += Q9.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7, IQuery<T8> Q8, IQuery<T9> Q9, IQuery<T10> Q10) : IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount + Q8.OperationCount + Q9.OperationCount + Q10.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
        plan.Add(Q8);
        plan.Add(Q9);
        plan.Add(Q10);
    }

    (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)]),
            Q8.ReadResultFrom(results[offset..(offset += Q8.OperationCount)]),
            Q9.ReadResultFrom(results[offset..(offset += Q9.OperationCount)]),
            Q10.ReadResultFrom(results[offset..(offset += Q10.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7, IQuery<T8> Q8, IQuery<T9> Q9, IQuery<T10> Q10, IQuery<T11> Q11) : IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount + Q8.OperationCount + Q9.OperationCount + Q10.OperationCount + Q11.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
        plan.Add(Q8);
        plan.Add(Q9);
        plan.Add(Q10);
        plan.Add(Q11);
    }

    (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)]),
            Q8.ReadResultFrom(results[offset..(offset += Q8.OperationCount)]),
            Q9.ReadResultFrom(results[offset..(offset += Q9.OperationCount)]),
            Q10.ReadResultFrom(results[offset..(offset += Q10.OperationCount)]),
            Q11.ReadResultFrom(results[offset..(offset += Q11.OperationCount)])
        );
    }
}

internal sealed record CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(IQuery<T1> Q1, IQuery<T2> Q2, IQuery<T3> Q3, IQuery<T4> Q4, IQuery<T5> Q5, IQuery<T6> Q6, IQuery<T7> Q7, IQuery<T8> Q8, IQuery<T9> Q9, IQuery<T10> Q10, IQuery<T11> Q11, IQuery<T12> Q12) : IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>
{
    public int OperationCount
        => Q1.OperationCount + Q2.OperationCount + Q3.OperationCount + Q4.OperationCount + Q5.OperationCount + Q6.OperationCount + Q7.OperationCount + Q8.OperationCount + Q9.OperationCount + Q10.OperationCount + Q11.OperationCount + Q12.OperationCount;

    void IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>.AddTo(QueryPlan plan)
    {
        plan.Add(Q1);
        plan.Add(Q2);
        plan.Add(Q3);
        plan.Add(Q4);
        plan.Add(Q5);
        plan.Add(Q6);
        plan.Add(Q7);
        plan.Add(Q8);
        plan.Add(Q9);
        plan.Add(Q10);
        plan.Add(Q11);
        plan.Add(Q12);
    }

    (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>.ReadResultFrom(params scoped ReadOnlySpan<ReadOnlyMemory<byte>> results)
    {
        int offset = 0;

        return (
            Q1.ReadResultFrom(results[offset..(offset += Q1.OperationCount)]),
            Q2.ReadResultFrom(results[offset..(offset += Q2.OperationCount)]),
            Q3.ReadResultFrom(results[offset..(offset += Q3.OperationCount)]),
            Q4.ReadResultFrom(results[offset..(offset += Q4.OperationCount)]),
            Q5.ReadResultFrom(results[offset..(offset += Q5.OperationCount)]),
            Q6.ReadResultFrom(results[offset..(offset += Q6.OperationCount)]),
            Q7.ReadResultFrom(results[offset..(offset += Q7.OperationCount)]),
            Q8.ReadResultFrom(results[offset..(offset += Q8.OperationCount)]),
            Q9.ReadResultFrom(results[offset..(offset += Q9.OperationCount)]),
            Q10.ReadResultFrom(results[offset..(offset += Q10.OperationCount)]),
            Q11.ReadResultFrom(results[offset..(offset += Q11.OperationCount)]),
            Q12.ReadResultFrom(results[offset..(offset += Q12.OperationCount)])
        );
    }
}
