// <auto-generated/>
namespace EtherSharp.Query;

public partial interface IQuery
{
    /// <summary>
    /// Combines 2 queries into a single query that returns a tuple of both results.
    /// </summary>
    public static IQuery<(T1, T2)> Combine<T1, T2>(IQuery<T1> q1, IQuery<T2> q2)
        => new Query<(T1, T2)>(
            [.. q1.Queries, .. q2.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 3 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3)> Combine<T1, T2, T3>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3)
        => new Query<(T1, T2, T3)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 4 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4)> Combine<T1, T2, T3, T4>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4)
        => new Query<(T1, T2, T3, T4)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 5 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5)> Combine<T1, T2, T3, T4, T5>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5)
        => new Query<(T1, T2, T3, T4, T5)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries, .. q5.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)]),
                    q5.ReadResultFrom(results[offset..(offset += q5.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 6 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6)> Combine<T1, T2, T3, T4, T5, T6>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6)
        => new Query<(T1, T2, T3, T4, T5, T6)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries, .. q5.Queries, .. q6.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)]),
                    q5.ReadResultFrom(results[offset..(offset += q5.Queries.Count)]),
                    q6.ReadResultFrom(results[offset..(offset += q6.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 7 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7)> Combine<T1, T2, T3, T4, T5, T6, T7>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7)
        => new Query<(T1, T2, T3, T4, T5, T6, T7)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries, .. q5.Queries, .. q6.Queries, .. q7.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)]),
                    q5.ReadResultFrom(results[offset..(offset += q5.Queries.Count)]),
                    q6.ReadResultFrom(results[offset..(offset += q6.Queries.Count)]),
                    q7.ReadResultFrom(results[offset..(offset += q7.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 8 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8)> Combine<T1, T2, T3, T4, T5, T6, T7, T8>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8)
        => new Query<(T1, T2, T3, T4, T5, T6, T7, T8)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries, .. q5.Queries, .. q6.Queries, .. q7.Queries, .. q8.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)]),
                    q5.ReadResultFrom(results[offset..(offset += q5.Queries.Count)]),
                    q6.ReadResultFrom(results[offset..(offset += q6.Queries.Count)]),
                    q7.ReadResultFrom(results[offset..(offset += q7.Queries.Count)]),
                    q8.ReadResultFrom(results[offset..(offset += q8.Queries.Count)])
                );
            }
        );
    /// <summary>
    /// Combines 9 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9)> Combine<T1, T2, T3, T4, T5, T6, T7, T8, T9>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8, IQuery<T9> q9)
        => new Query<(T1, T2, T3, T4, T5, T6, T7, T8, T9)>(
            [.. q1.Queries, .. q2.Queries, .. q3.Queries, .. q4.Queries, .. q5.Queries, .. q6.Queries, .. q7.Queries, .. q8.Queries, .. q9.Queries],
            results =>
            {
                int offset = 0;

                return (
                    q1.ReadResultFrom(results[offset..(offset += q1.Queries.Count)]),
                    q2.ReadResultFrom(results[offset..(offset += q2.Queries.Count)]),
                    q3.ReadResultFrom(results[offset..(offset += q3.Queries.Count)]),
                    q4.ReadResultFrom(results[offset..(offset += q4.Queries.Count)]),
                    q5.ReadResultFrom(results[offset..(offset += q5.Queries.Count)]),
                    q6.ReadResultFrom(results[offset..(offset += q6.Queries.Count)]),
                    q7.ReadResultFrom(results[offset..(offset += q7.Queries.Count)]),
                    q8.ReadResultFrom(results[offset..(offset += q8.Queries.Count)]),
                    q9.ReadResultFrom(results[offset..(offset += q9.Queries.Count)])
                );
            }
        );
}
