// <auto-generated/>
namespace EtherSharp.Query;

public partial interface IQuery
{
    /// <summary>
    /// Combines 2 queries into a single query that returns a tuple of both results.
    /// </summary>
    public static IQuery<(T1, T2)> Combine<T1, T2>(IQuery<T1> q1, IQuery<T2> q2)
        => new CombinedQuery<T1, T2>(q1, q2);
    /// <summary>
    /// Combines 3 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3)> Combine<T1, T2, T3>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3)
        => new CombinedQuery<T1, T2, T3>(q1, q2, q3);
    /// <summary>
    /// Combines 4 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4)> Combine<T1, T2, T3, T4>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4)
        => new CombinedQuery<T1, T2, T3, T4>(q1, q2, q3, q4);
    /// <summary>
    /// Combines 5 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5)> Combine<T1, T2, T3, T4, T5>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5)
        => new CombinedQuery<T1, T2, T3, T4, T5>(q1, q2, q3, q4, q5);
    /// <summary>
    /// Combines 6 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6)> Combine<T1, T2, T3, T4, T5, T6>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6>(q1, q2, q3, q4, q5, q6);
    /// <summary>
    /// Combines 7 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7)> Combine<T1, T2, T3, T4, T5, T6, T7>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7>(q1, q2, q3, q4, q5, q6, q7);
    /// <summary>
    /// Combines 8 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8)> Combine<T1, T2, T3, T4, T5, T6, T7, T8>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8>(q1, q2, q3, q4, q5, q6, q7, q8);
    /// <summary>
    /// Combines 9 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9)> Combine<T1, T2, T3, T4, T5, T6, T7, T8, T9>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8, IQuery<T9> q9)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9>(q1, q2, q3, q4, q5, q6, q7, q8, q9);
    /// <summary>
    /// Combines 10 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)> Combine<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8, IQuery<T9> q9, IQuery<T10> q10)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(q1, q2, q3, q4, q5, q6, q7, q8, q9, q10);
    /// <summary>
    /// Combines 11 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)> Combine<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8, IQuery<T9> q9, IQuery<T10> q10, IQuery<T11> q11)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11);
    /// <summary>
    /// Combines 12 queries into a single query that returns a tuple of all results.
    /// </summary>
    public static IQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)> Combine<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(IQuery<T1> q1, IQuery<T2> q2, IQuery<T3> q3, IQuery<T4> q4, IQuery<T5> q5, IQuery<T6> q6, IQuery<T7> q7, IQuery<T8> q8, IQuery<T9> q9, IQuery<T10> q10, IQuery<T11> q11, IQuery<T12> q12)
        => new CombinedQuery<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12);
}
